#!/usr/bin/env python3
"""Build web_research.json from URLs collected in main-thread WebSearches.

Each URL block was sourced via WebSearch (grouped by domain). The synthesised
summary fields below were paraphrased from search-result snippets and are
intentionally short. The shipped HTML cites these URLs but never reads them at
runtime, satisfying the offline requirement.
"""
import json
from pathlib import Path

OUT = Path("/Users/mike/cissp/web_research.json")
CAPTURED = "2026-04-26"


def src(url, title, summary="", extract=""):
    return {
        "url": url,
        "title": title,
        "captured": CAPTURED,
        "summary": summary,
        "extract": extract,
    }


# Domain 1: Security and Risk Management (16%)
D1 = [
    src("https://destcert.com/resources/domain-1-security-and-risk-management/",
        "DestCert: Unraveling CISSP Domain 1 — Security and Risk Management",
        "Domain 1 (16%) covers governance, risk, compliance, BCP/DRP, threat modeling, professional ethics."),
    src("https://lognpacific.com/free-certification-practice-tests/free-cissp-practice-questions/cissp-domain-1-security-and-risk-management-domain-1-cissp-exam/",
        "LognPacific: Free CISSP Domain 1 Practice Questions",
        "Free practice question bank focused on Domain 1 risk and governance topics."),
    src("https://quizlet.com/87472460/official-isc-cissp-domain-1-security-and-risk-management-flash-cards/",
        "Quizlet: Official ISC2 CISSP Domain 1 flashcards",
        "Crowd-sourced flashcards aligned to the official Sybex study guide chapters."),
    src("https://www.techtarget.com/searchsecurity/quiz/Cybersecurity-risk-management-CISSP-practice-exam",
        "TechTarget: CISSP Domain 1 quiz — Security and risk management",
        "Practice quiz with multi-choice questions on inherent vs residual risk, governance frameworks."),
    src("https://cissprep.net/domain-1-security-and-risk-management/",
        "CISSPrep: Domain 1 — Security and Risk Management",
        "Free study notes covering CIA, governance, codes of ethics, BCP, risk frameworks."),
    src("https://quizlet.com/715975934/cissp-official-practice-questions-security-and-risk-management-domain-1-flash-cards/",
        "Quizlet: CISSP Official Practice Questions Domain 1",
        "Practice question deck aligned to the Sybex official practice tests."),
    src("https://quizlet.com/529593082/cissp-practice-testschapter-1security-risk-management-domain-1-flash-cards/",
        "Quizlet: CISSP Practice Tests Chapter 1 — Security & Risk Management",
        "Chapter-1 practice questions; tests due care vs due diligence and policy hierarchy."),
    src("https://www.easylearn.ing/course/cissp-domain-1-practice-questions",
        "EasyLearn: Ace the CISSP Exam — Domain 1 practice questions",
        "Curated practice questions for Domain 1 with explanations."),
    src("https://www.gulftalent.com/online/courses/cissp-domain-1-security-risk-management-practice-questions-32019",
        "GulfTalent: CISSP Domain 1 practice questions course",
        "Online course with manager-mindset Domain 1 questions."),
    src("https://cissprep.net/domain-1-quizzes-2024/",
        "CISSPrep: Domain 1 Quizzes 2024",
        "Updated 2024 quiz set aligned to the new exam outline."),
    src("https://wentzwu.com/2021/10/03/cissp-practice-questions-20211002/",
        "Wentz Wu: CISSP Practice Questions 20211002",
        "Sample exam questions with detailed manager-mindset explanations."),
    src("https://www.examtopics.com/discussions/isc/view/81332-exam-cissp-topic-1-question-327-discussion/",
        "ExamTopics: Exam CISSP topic 1 question 327 discussion",
        "Community discussion of an ALE/SLE quantitative risk question."),
    src("https://wentzwu.com/2019/10/20/cissp-practice-questions-20191021/",
        "Wentz Wu: CISSP Practice Questions 20191021",
        "Older Wentz Wu set; covers ARO/ALE calculation mechanics."),
    src("https://wentzwu.com/2020/04/05/cissp-practice-questions-20200406/",
        "Wentz Wu: CISSP Practice Questions 20200406",
        "Includes several BIA/MTD/RTO scenario questions."),
    src("https://www.examtopics.com/exams/isc/cissp/view/",
        "ExamTopics: CISSP Exam — Free Q&As",
        "Large community-maintained CISSP question bank with discussion."),
    src("https://wentzwu.com/2020/04/05/common-bia-terminologies/",
        "Wentz Wu: Common BIA Terminologies",
        "Cheat sheet defining MTD, RTO, RPO, WRT, MTBF with examples."),
    src("https://wentzwu.com/2022/01/26/cissp-practice-questions-20220126/",
        "Wentz Wu: CISSP Practice Questions 20220126",
        "Practice set mixing governance, risk, and threat-modeling questions."),
    src("https://destcert.com/resources/threat-modeling-methodologies/",
        "DestCert: Threat Modeling Methodologies — STRIDE, PASTA, DREAD",
        "Comparison of major threat-modeling methodologies for CISSP candidates."),
    src("https://www.softwaresecured.com/post/comparison-of-stride-dread-pasta",
        "SoftwareSecured: Comparison of STRIDE, DREAD & PASTA",
        "Side-by-side comparison of three threat-modeling techniques."),
    src("https://medium.com/step-by-step-cissp-ccsp/cissp-study-notes-threat-modeling-56bccfbab210",
        "Medium / Step by Step CISSP: Threat Modeling notes",
        "Note set summarising STRIDE/PASTA/DREAD/VAST approaches."),
    src("https://www.cisspcybertraining.com/blog/cct-149",
        "CISSP Cyber Training: CCT 149 — Threat Modeling & STRIDE questions",
        "Podcast/blog with sample STRIDE questions and answer rationale."),
    src("https://www.threatonthewire.com/cissp-threat-modeling-stride-pasta-managers-role/",
        "ThreatOnTheWire: Threat Modeling for Security Leaders",
        "Manager-perspective explanation of when to choose STRIDE vs PASTA."),
    src("https://blog.balancedsec.com/p/understanding-cissp-domain-1-security",
        "BalancedSec: Understanding CISSP Domain 1",
        "Blog series with detailed Domain 1 review."),
    src("https://www.youtube.com/watch?v=VoiHRBaV8Xk",
        "YouTube: CISSP Threat Modeling — STRIDE, DREAD, PASTA, VAST",
        "Video walkthrough of all four threat models."),
    src("https://csrc.nist.gov/pubs/sp/800/30/r1/final",
        "NIST SP 800-30 Rev 1: Guide for Conducting Risk Assessments",
        "Authoritative NIST risk assessment process referenced by CISSP CBK."),
    src("https://csrc.nist.gov/pubs/sp/800/37/r2/final",
        "NIST SP 800-37 Rev 2: Risk Management Framework (RMF)",
        "Six-step RMF; Categorize → Select → Implement → Assess → Authorize → Monitor."),
    src("https://www.nist.gov/cyberframework",
        "NIST Cybersecurity Framework (CSF) 2.0",
        "Govern, Identify, Protect, Detect, Respond, Recover functions."),
    src("https://www.iso.org/standard/27001",
        "ISO/IEC 27001 — Information security management",
        "Establishes ISMS requirements; PDCA cycle and Annex A controls."),
    src("https://www.isc2.org/Ethics",
        "ISC2 Code of Ethics",
        "Four canons every CISSP must order from highest to lowest priority."),
    src("https://www.isc2.org/-/media/Project/ISC2/Main/Media/documents/exam-outlines/CISSP-Exam-Outline-April-2024-English.pdf",
        "ISC2: CISSP Detailed Content Outline (April 2024)",
        "Authoritative outline; D1 = 16% (was 15%), D8 = 10% (was 11%)."),
    src("https://destcert.com/resources/cissp-exam-refresh-2024-what-you-need-to-know/",
        "DestCert: CISSP 2024 Update — Exam Format & Syllabus Changes",
        "Summary of D1 weight increase and D8 decrease in April 2024."),
    src("https://www.isc2.org/Insights/2023/11/Changes-to-CISSP-Exam-Weighting",
        "ISC2 Insights: Changes to the CISSP Exam Weighting",
        "Official explanation of the 2024 weight changes."),
]

# Domain 2: Asset Security (10%)
D2 = [
    src("https://www.techtarget.com/searchsecurity/quiz/CISSP-Domain-2-quiz-Data-security-control-asset-protection",
        "TechTarget: CISSP Domain 2 quiz",
        "Practice quiz on data security controls and asset protection."),
    src("https://destcert.com/resources/domain-2-asset-security/",
        "DestCert: Asset Security in CISSP Domain 2",
        "Domain 2 essentials; 10% weighting; data ownership and lifecycle focus."),
    src("https://blog.balancedsec.com/p/understanding-cissp-domain-2-asset",
        "BalancedSec: Understanding CISSP Domain 2 — Asset Security",
        "Blog explaining classification, ownership, retention, sanitisation."),
    src("https://quizlet.com/217188025/cissp-practice-tests-chapter-2-asset-security-domain-2-flash-cards/",
        "Quizlet: CISSP Practice Tests Chapter 2 — Asset Security",
        "Flashcard deck of practice questions for Domain 2."),
    src("https://resources.infosecinstitute.com/certification/cissp-domain-2-asset-security-need-know-exam/",
        "Infosec Institute: CISSP Domain 2 — Asset Security",
        "Topic guide on classification, retention, DLP, sanitisation."),
    src("https://quizlet.com/1019457792/cissp-domain-2-asset-security-flash-cards/",
        "Quizlet: CISSP Domain 2 Asset Security flashcards",
        "Updated 2024-aligned card deck for Asset Security."),
    src("https://certifiedcissp.com/domain-2-asset-security/",
        "CertifiedCISSP: Domain 2 Asset Security",
        "Free Domain 2 study notes."),
    src("https://www.threatonthewire.com/cissp-domain-2-ownership-information-assets/",
        "ThreatOnTheWire: Ownership of Information and Assets",
        "Owner is a senior business leader; custodian implements at owner direction."),
    src("https://infosectests.com/cissp-study-references/domain-2-asset-security/",
        "InfosecTests: Domain 2 Asset Security references",
        "Study references and quizzes for Domain 2."),
    src("https://jefferywmoore.github.io/CISSP-Study-Resources/CISSP-Domain-2-2024+Objectives.html",
        "Jeffery W Moore: CISSP-Study-Resources — Domain 2 Objectives 2024",
        "Open-source study notes mapped to 2024 outline."),
    src("https://inventivehq.com/blog/nist-800-88-media-sanitization-complete-guide",
        "InventiveHQ: NIST 800-88 — Clear, Purge, Destroy Methods Explained",
        "NIST 800-88 sanitisation methods overview."),
    src("https://csrc.nist.gov/pubs/sp/800/88/r1/final",
        "NIST SP 800-88 Rev 1: Guidelines for Media Sanitization",
        "Authoritative NIST sanitisation guidance: Clear/Purge/Destroy."),
    src("https://www.accountablehq.com/post/hard-drive-sanitization-how-to-securely-erase-data-nist-800-88-guide",
        "AccountableHQ: Hard Drive Sanitization — NIST 800-88 Guide",
        "Plain-language explanation of NIST 800-88 sanitisation choices."),
    src("https://csrc.nist.gov/pubs/sp/800/88/r2/final",
        "NIST SP 800-88 Rev 2",
        "Latest NIST sanitisation revision; introduces additional crypto-erase guidance."),
    src("https://nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-88r1.pdf",
        "NIST 800-88r1 PDF (NVLPubs)",
        "Official PDF of NIST 800-88 Rev 1."),
    src("https://jetico.com/blog/nist-sp-800-88-guidelines-media-sanitization-explained/",
        "Jetico: NIST SP 800-88 Guidelines for Media Sanitization Explained",
        "Vendor explainer covering sanitisation methods and compliance."),
    src("https://www.goworkwize.com/blog/what-is-nist-800-88-guide",
        "Workwize: What is NIST 800-88? Guide to Media Sanitization",
        "Practical NIST 800-88 guide for IT operations teams."),
    src("https://www.pearsonitcertification.com/articles/article.aspx?p=3128866&seqNum=20",
        "Pearson IT Certification: Data Remanence and Decommissioning",
        "Asset Security article on residual data and end-of-life destruction."),
    src("https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-88r2.pdf",
        "NIST SP 800-88r2 PDF",
        "Authoritative PDF of NIST 800-88 Rev 2."),
    src("https://destcert.com/resources/scoping-tailoring-security-controls-for-businesses/",
        "DestCert: Scoping & Tailoring Security Controls",
        "Scoping excludes irrelevant controls; tailoring modifies remaining ones."),
    src("https://www.learnsecuritymanagement.com/cissp-insight-scoping-vs-tailoring",
        "LearnSecurityManagement: Scoping vs Tailoring",
        "CISSP-focused comparison of scoping versus tailoring."),
    src("https://www.pearsonitcertification.com/articles/article.aspx?p=3167978&seqNum=7",
        "Pearson IT Certification: Data Security Controls",
        "Asset Security article on technical and admin data controls."),
    src("https://community.isc2.org/t5/Tech-Talk/NIST-SP-800-53-REV-5-Final-Published/td-p/39493",
        "ISC2 Community: NIST SP 800-53 Rev 5 Final Published",
        "Member discussion of the impact of NIST 800-53 Rev 5."),
    src("https://www.scribd.com/document/755480430/Cissp-Mind-Map-100-Practice-Questions-Combo",
        "Scribd: CISSP Mind Map + 100 Practice Questions Combo",
        "Mind-map style review aid combined with practice questions."),
    src("https://nvlpubs.nist.gov/nistpubs/legacy/sp/nistspecialpublication800-53ar1.pdf",
        "NIST SP 800-53A Rev 1",
        "Guide for Assessing Security Controls — referenced by CISSP CBK."),
    src("https://wentzwu.com/2022/02/08/cissp-practice-questions-20220208/",
        "Wentz Wu: CISSP Practice Questions 20220208",
        "Includes Asset Security scoping/tailoring questions."),
    src("https://wentzwu.com/2020/06/19/cissp-practice-questions-20200620/",
        "Wentz Wu: CISSP Practice Questions 20200620",
        "Older set with data ownership scenarios."),
    src("https://community.isc2.org/t5/Tech-Talk/Help-with-the-NIST-800-53-controls-list/td-p/5893",
        "ISC2 Community: Help with the NIST 800-53 controls list",
        "Member thread mapping NIST controls to CISSP topics."),
    src("https://www.dhs.gov/sites/default/files/publications/4300A-Handbook-Attachment-M-Tailoring-NIST-800-53-Security-Controls.pdf",
        "DHS 4300A Attachment M: Tailoring NIST 800-53",
        "Government tailoring example referenced in Domain 2 study guides."),
    src("https://csrc.nist.gov/pubs/sp/800/60/v1/r1/final",
        "NIST SP 800-60 Vol I Rev 1: Mapping Information Types to Security Categories",
        "FIPS-199 categorisation guidance for asset classification."),
    src("https://csrc.nist.gov/pubs/fips/199/final",
        "FIPS PUB 199: Standards for Security Categorization",
        "Low/Moderate/High impact categorisation for federal information."),
    src("https://gdpr-info.eu/",
        "GDPR Info: General Data Protection Regulation full text",
        "Useful for Domain 2 privacy and data subject rights questions."),
]

# Domain 3: Security Architecture & Engineering (13%)
D3 = [
    src("https://blog.balancedsec.com/p/understanding-cissp-domain-3-security",
        "BalancedSec: Understanding CISSP Domain 3 — Part 1",
        "Domain 3 study notes on architecture and security models."),
    src("https://quizlet.com/393367250/cissp-domain-3-security-architecture-and-engineering-flash-cards/",
        "Quizlet: CISSP Domain 3 Security Architecture flashcards",
        "Flashcards on Bell-LaPadula, Biba, Clark-Wilson, Brewer-Nash, etc."),
    src("https://siteforinfotech.com/2025/09/cissp-domain-3-practice-test-100-best-questions-that-actually-matter.html",
        "InfoTechSite: CISSP Domain 3 Practice Test — 100 questions",
        "100-question practice set focused on Domain 3 hard topics."),
    src("https://destcert.com/resources/domain-3-security-architecture-and-engineering/",
        "DestCert: CISSP Domain 3 — Comprehensive Security Architecture Guide",
        "Domain 3 (13%) covering security models, crypto, secure design."),
    src("https://www.cybernous.com/domain-summaries/cissp-domain-3-security-architecture-and-engineering",
        "Cybernous: CISSP Domain 3 — Full Study Summary",
        "Long-form Domain 3 review by Manoj Sharma."),
    src("https://www.infosectrain.com/blog/domain-3-security-architecture-and-engineering",
        "InfosecTrain: Domain 3 — Security Architecture and Engineering",
        "Topic-by-topic Domain 3 walkthrough."),
    src("https://www.techtarget.com/searchsecurity/quiz/Security-Engineering-CISSP-Domain-3-practice-quiz",
        "TechTarget: CISSP Domain 3 quiz",
        "Practice quiz covering security models and cryptographic primitives."),
    src("https://cissprep.net/security-access-control-models/",
        "CISSPrep: Security Models & Engineering",
        "Comparison of MAC/DAC models and reference monitor concepts."),
    src("https://www.cisspcybertraining.com/blog/indian-cctv-and-cissp-practice-test-domain-3",
        "CISSP Cyber Training: Domain 3 practice test",
        "Practice questions tied to physical security and access models."),
    src("https://siit.co/blog/cissp-security-models-bell-lapadula-biba-and-clark-wilson-in-exams/51331",
        "SIIT: CISSP Security Models in Exams",
        "Exam-style scenarios mapping models to security goals."),
    src("https://www.threatonthewire.com/cissp-domain-3-securing-hardware-platform/",
        "ThreatOnTheWire: Securing the Hardware Platform — CISSP Domain 3",
        "TPM, HSM, secure boot, side-channel issues."),
    src("https://www.examtopics.com/discussions/isc/view/81799-exam-cissp-topic-1-question-98-discussion/",
        "ExamTopics: CISSP topic 1 question 98 discussion",
        "Community discussion of a hardware/security-architecture question."),
    src("https://www.examcollection.com/blog/cissp-exam-prep-deep-dive-into-covert-channel-analysis/",
        "ExamCollection: Deep Dive into Covert Channel Analysis",
        "Storage vs timing covert channels and detection strategies."),
    src("https://www.cybrary.it/blog/covert-channel-analysis",
        "Cybrary: CISSP Study Guide — Covert Channel Analysis",
        "Differentiates covert from overt channels for CISSP candidates."),
    src("https://www.wolfssl.com/difference-hsm-tpm-secure-enclave-secure-element-hardware-root-trust/",
        "wolfSSL: Difference between HSM, TPM, Secure Enclave, Secure Element",
        "Compares different hardware roots of trust."),
    src("https://www.hsmpress.ca/cissp/3-4-understand-security-capabilities-of-information-systems-e-g-memory-protection-trusted-platform-module-tpm-encryption-decryption/",
        "HSM Press: CISSP 3.4 — Memory protection, TPM, encryption",
        "Subdomain reference for capabilities of information systems."),
    src("https://wentzwu.com/2020/09/28/cissp-practice-questions-20200929/",
        "Wentz Wu: CISSP Practice Questions 20200929",
        "Domain 3 questions including hardware and crypto."),
    src("https://www.usenix.org/system/files/sec20-moghimi-tpm.pdf",
        "USENIX: TPM-Fail — TPM meets Timing and Lattice Attacks",
        "Academic paper on TPM side-channel vulnerabilities."),
    src("https://destcert.com/resources/types-of-ciphers/",
        "DestCert: Types of Ciphers — ECB, CBC, OFB & More",
        "Block-cipher modes of operation explained for CISSP."),
    src("https://www.examcollection.com/blog/cryptography-and-encryption-a-cissp-study-companion/",
        "ExamCollection: Cryptography and Encryption — CISSP Companion",
        "Crypto study companion: symmetric, asymmetric, hashing, PKI."),
    src("https://destcert.com/resources/cryptography-mindmap-cissp-domain-3/",
        "DestCert: Cryptography MindMap — CISSP Domain 3",
        "Visual mind map of crypto for Domain 3."),
    src("https://itknowledgebases.com/block-cipher-modes-of-operation-explained-ecb-vs-cbc-vs-ctr-vs-gcm-cissp-guide/",
        "ITKnowledgeBases: Block Cipher Modes Explained — CISSP Guide",
        "ECB vs CBC vs CTR vs GCM with CISSP context."),
    src("https://blog.balancedsec.com/p/understanding-cissp-domain-3-security-ace",
        "BalancedSec: Understanding CISSP Domain 3 — Part 2",
        "Continuation focused on cryptography and PKI."),
    src("https://thomasrayner.ca/cissp-study-notes-ch6/",
        "Thomas Rayner: CISSP Study Notes Chapter 6 — Cryptography",
        "Chapter 6 cryptography study notes from Sybex."),
    src("https://www.threatonthewire.com/cissp-domain-3-cryptography-essentials/",
        "ThreatOnTheWire: Cryptography Essentials for Security Architects",
        "Manager-perspective cryptography review."),
    src("https://www.haikel-fazzani.eu.org/blog/post/aes-encryption-modes-gcm-cbc-ctr",
        "Haikel Fazzani: Understanding AES Encryption Modes",
        "Practical AES mode explanation."),
    src("https://www.techtarget.com/searchsecurity/feature/CISSP-cryptography-training-Components-protocols-and-authentication",
        "TechTarget: CISSP cryptography training",
        "Cryptography training feature covering components and protocols."),
    src("https://www.slideshare.net/KarthikeyanDhayalan1/cissp-chapter-3-cryptography",
        "SlideShare: CISSP Chapter 3 Cryptography",
        "Slide deck summarising Chapter 3 cryptography content."),
    src("https://csrc.nist.gov/pubs/sp/800/57/pt1/r5/final",
        "NIST SP 800-57 Part 1 Rev 5: Recommendation for Key Management",
        "Authoritative NIST key-management guidance."),
    src("https://csrc.nist.gov/pubs/fips/140/3/final",
        "FIPS 140-3: Security Requirements for Cryptographic Modules",
        "Standard for cryptographic module validation."),
    src("https://www.commoncriteriaportal.org/cc/",
        "Common Criteria Portal",
        "Common Criteria EAL evaluation levels (EAL1-EAL7) authoritative source."),
    src("https://csrc.nist.gov/pubs/sp/800/53/r5/upd1/final",
        "NIST SP 800-53 Rev 5: Security and Privacy Controls",
        "Catalog of security and privacy controls referenced across all domains."),
    src("https://destcert.com/resources/vulnerabilities-in-systems-mindmap-cissp-domain-3/",
        "DestCert: Vulnerabilities in Systems MindMap — Domain 3",
        "MindMap for system vulnerabilities (race conditions, covert channels)."),
]

# Domain 4: Communication and Network Security (13%)
D4 = [
    src("https://destcert.com/resources/cissp-domain-4-communication-and-network-security/",
        "DestCert: CISSP Domain 4 — Guide to Communication and Network Security",
        "Domain 4 (13%) walkthrough: OSI/TCP-IP, secure protocols, wireless."),
    src("https://siteforinfotech.com/2025/10/take-this-cissp-domain-4-practice-test.html",
        "InfoTechSite: CISSP Domain 4 Practice Test — 100 questions",
        "Practice test focused on Domain 4 networking topics."),
    src("https://cissprep.net/domain-4-concepts-and-terms/",
        "CISSPrep: Domain 4 Concepts and Terms",
        "Glossary of Domain 4 networking terms for the exam."),
    src("https://blog.balancedsec.com/p/understanding-cissp-domain-4-communication",
        "BalancedSec: Understanding CISSP Domain 4 — Part 1",
        "Domain 4 study notes part 1."),
    src("https://www.udemy.com/course/cissp-domain-4-communication-and-network-security/",
        "Udemy: CISSP Domain 4 — Communication and Network Security",
        "Paid course with 200+ scenario-based questions."),
    src("https://resources.infosecinstitute.com/certification/communications-and-network-security/",
        "Infosec Institute: CISSP Domain 4 — Communications and Network Security",
        "Topic guide for Domain 4."),
    src("https://blog.balancedsec.com/p/understanding-cissp-domain-4-communication-7ae",
        "BalancedSec: Understanding CISSP Domain 4 — Part 2",
        "Domain 4 study notes part 2."),
    src("https://quizlet.com/217188092/cissp-practice-tests-chapter-4-communication-and-network-security-domain-4-flash-cards/",
        "Quizlet: CISSP Practice Tests Chapter 4 — Communication and Network Security",
        "Flashcards aligned to chapter 4 of the official practice tests."),
    src("https://www.techtarget.com/searchsecurity/quiz/CISSP-Domain-4-Test-your-expertise-of-network-security-basics",
        "TechTarget: CISSP Domain 4 quiz — Network security basics",
        "Quiz on OSI, VPNs, firewalls, network attacks."),
    src("https://jefferywmoore.github.io/CISSP-Study-Resources/CISSP-Domain-4-2024+Objectives.html",
        "Jeffery W Moore: CISSP-Study-Resources — Domain 4 Objectives 2024",
        "Open-source 2024-aligned Domain 4 objectives."),
    src("https://smallstep.com/blog/eaptls-certificate-wifi/",
        "SmallStep: Certificate Based Wi-Fi Authentication with RADIUS and EAP-TLS",
        "Practical EAP-TLS with RADIUS deployment guide."),
    src("https://www.techtarget.com/searchnetworking/feature/Choosing-the-right-flavor-of-8021X",
        "TechTarget: Overview of 802.1X authentication methods and EAP",
        "Compares EAP-TLS, PEAP, EAP-TTLS, EAP-FAST for 802.1X."),
    src("https://www.cisco.com/c/en/us/support/docs/wireless-mobility/wireless-lan-wlan/213543-configure-eap-tls-flow-with-ise.html",
        "Cisco: Understand and Configure EAP-TLS with AireOS WLC and ISE",
        "Cisco-specific EAP-TLS reference design."),
    src("https://securew2.com/blog/802-1x-eap-tls-authentication-flow-explained",
        "SecureW2: 802.1X EAP-TLS Authentication Flow",
        "Step-by-step EAP-TLS handshake explanation."),
    src("https://www.ironwifi.com/blogs/best-eap-methods-wifi/",
        "IronWiFi: Best EAP Methods for Wi-Fi — EAP-TLS vs PEAP vs EAP-TTLS",
        "Comparison of dominant EAP methods in WPA2/3 Enterprise."),
    src("https://www.cloudi-fi.com/blog/wpa2-enterprise-802-1x",
        "Cloudi-Fi: WPA2/3-Enterprise — Secure Wi-Fi with 802.1X authentication",
        "Enterprise wireless security explainer."),
    src("https://wentzwu.com/2021/08/15/cissp-practice-questions-20210815/",
        "Wentz Wu: CISSP Practice Questions 20210815",
        "Includes zero-trust and microsegmentation questions."),
    src("https://www.cisspcybertraining.com/blog/uk-manufacture-attacks-cissp-practice-test",
        "CISSP Cyber Training: UK Manufacture Attacks practice test",
        "Network attack-pattern practice questions."),
    src("https://blog.iptel.com.au/blog/cisco-sd-access-micro-segmentation-explained",
        "iptel: Cisco SD-Access Micro Segmentation Explained",
        "Vendor-agnostic microsegmentation concepts."),
    src("https://destcert.com/resources/software-defined-networking-sdn/",
        "DestCert: Software-Defined Networking (SDN) for Scalable Security",
        "SDN concepts every CISSP needs."),
    src("https://ipwithease.com/microsegmentation-vs-zero-trust/",
        "IPwithEase: Microsegmentation vs Zero Trust",
        "Differentiates microsegmentation from full zero-trust architecture."),
    src("https://www.networkworld.com/article/966394/zero-trust-networking-ztn-don-t-trust-anything.html",
        "NetworkWorld: Zero Trust Networking — don't trust anything",
        "Mainstream introduction to zero-trust networking."),
    src("https://www.cisco.com/c/en/us/td/docs/dcn/whitepapers/securing-datacenters-with-microsegmentation-and-vxlan-gpo.html",
        "Cisco: Securing Data Centers with Microsegmentation using VXLAN GPO",
        "Vendor whitepaper on VXLAN microsegmentation."),
    src("https://www.wwt.com/article/cisco-zero-trust-a-holistic-approach",
        "WWT: Cisco Zero Trust — A Holistic Approach",
        "Holistic zero-trust architecture overview."),
    src("https://duo.com/learn/zero-trust-segmentation",
        "Cisco Duo: Zero Trust Segmentation Guide for Security Leaders",
        "Manager-level zero-trust segmentation guide."),
    src("https://datatracker.ietf.org/doc/html/rfc8446",
        "RFC 8446: TLS 1.3",
        "Authoritative TLS 1.3 specification."),
    src("https://datatracker.ietf.org/doc/html/rfc4301",
        "RFC 4301: Security Architecture for the Internet Protocol (IPsec)",
        "IPsec architecture document."),
    src("https://datatracker.ietf.org/doc/html/rfc7296",
        "RFC 7296: Internet Key Exchange Protocol Version 2 (IKEv2)",
        "IKEv2 specification used in modern IPsec deployments."),
    src("https://csrc.nist.gov/pubs/sp/800/207/final",
        "NIST SP 800-207: Zero Trust Architecture",
        "NIST authoritative zero-trust reference."),
    src("https://owasp.org/www-project-top-ten/",
        "OWASP Top Ten Project",
        "OWASP Top 10 web app risks (referenced for application-layer attacks)."),
    src("https://www.ietf.org/rfc/rfc4303.txt",
        "RFC 4303: IP Encapsulating Security Payload (ESP)",
        "ESP for IPsec confidentiality + integrity."),
    src("https://www.ietf.org/rfc/rfc4302.txt",
        "RFC 4302: IP Authentication Header (AH)",
        "AH integrity-only IPsec mode."),
]

# Domain 5: IAM (13%)
D5 = [
    src("https://destcert.com/resources/cissp-domain-5-identity-and-access-management-iam/",
        "DestCert: CISSP Domain 5 — Identity & Access Management",
        "Domain 5 (13%) coverage of IAM lifecycle, federation, MFA."),
    src("https://www.readynez.com/en/blog/understanding-cissp-domain-5-identity-and-access-management/",
        "Readynez: Understanding CISSP Domain 5 — IAM Explained",
        "Domain 5 study guide."),
    src("https://siteforinfotech.com/2025/10/cissp-domain-5-practice-test-100-questions-to-boost-your-confidence.html",
        "InfoTechSite: CISSP Domain 5 Practice Test — 100 questions",
        "100-question practice test focused on Domain 5."),
    src("https://isc2tc.org/wp-content/uploads/2016/05/CISSPStudyGroup_Domain_5_IdM_2016.pdf",
        "ISC2 Twin Cities Chapter: CISSP Study Group — Domain 5 IdM (2016)",
        "Local-chapter study deck on identity management."),
    src("https://www.cisspcybertraining.com/blog/cissp-rapid-review-domain-5",
        "CISSP Cyber Training: Rapid Review — Domain 5",
        "Rapid-review podcast/blog on Domain 5 high-yield topics."),
    src("https://cromwell-intl.com/cybersecurity/isc2-cissp/domain-5-identity-access-management.html",
        "Cromwell-Intl: CISSP Domain 5 — Identity & Access Management",
        "Free Domain 5 study guide."),
    src("https://resources.infosecinstitute.com/certification/identity-and-access-management/",
        "Infosec Institute: CISSP Domain 5 — Identity and Access Management",
        "IAM concept overview for CISSP."),
    src("https://www.pearsonitcertification.com/articles/article.aspx?p=2738310",
        "Pearson IT Certification: IAM Practice Questions",
        "Practice questions article from Pearson."),
    src("https://www.infosecinstitute.com/resources/cissp/identity-and-access-management/",
        "Infosec Institute (alt): IAM CISSP Domain 5",
        "Domain 5 reference page."),
    src("https://www.cybernous.com/domain-summaries/cissp-domain-5-summary-mastering-identity-access-management-iam",
        "Cybernous: CISSP Domain 5 Summary — Mastering IAM",
        "Domain 5 long-form summary by Manoj Sharma."),
    src("https://cissprep.net/federation-and-saml/",
        "CISSPrep: Federation and SAML",
        "Federation/SAML primer with example assertion exchanges."),
    src("https://destcert.com/resources/federated-identity-management/",
        "DestCert: Federated Identity Management — Extensive CISSP Guide",
        "FIM concepts (IdP, SP, RP) for the CISSP exam."),
    src("https://destcert.com/resources/saml-vs-sso/",
        "DestCert: SAML vs SSO — Key Differences in Single Sign-On",
        "Distinguishes SAML (a protocol) from SSO (a UX pattern)."),
    src("https://info-savvy.com/cissp-federated-identity-management-bk1d5t2st6/",
        "Info-Savvy: CISSP Federated Identity Management",
        "FIM topic in Domain 5 with examples."),
    src("https://www.fortinet.com/resources/cyberglossary/saml-vs-oauth",
        "Fortinet: What is SAML vs OAuth?",
        "Vendor explainer comparing SAML and OAuth."),
    src("https://www.securityjourney.com/post/analysis-of-common-federated-identity-protocols-openid-connect-vs-oauth-2.0-vs-saml-2.0",
        "SecurityJourney: OpenID Connect vs OAuth 2.0 vs SAML 2.0",
        "Side-by-side analysis of three common federation protocols."),
    src("https://commandline.ninja/saml-oauth-oidc/",
        "Commandline Ninja: SSO — SAML vs OAuth vs OIDC",
        "Plain-language SSO protocol comparison."),
    src("https://wentzwu.com/2021/01/06/cissp-practice-questions-20210107/",
        "Wentz Wu: CISSP Practice Questions 20210107",
        "Federation and Kerberos question set."),
    src("https://www.examcollection.com/blog/comprehensive-guide-to-single-sign-on-sso-for-cissp/",
        "ExamCollection: Comprehensive Guide to SSO for CISSP",
        "Long-form SSO study guide."),
    src("https://fedtechmagazine.com/article/2020/01/federated-identity-management-saml-vs-oauth-perfcon",
        "FedTech: Federated Identity Management — SAML vs OAuth",
        "Government IT perspective on federation choice."),
    src("https://cissprep.net/access-control-systems-multifactor-authentication-and-biometrics/",
        "CISSPrep: Access Control Systems, MFA & Biometrics",
        "MFA factors and biometric performance metrics for CISSP."),
    src("https://medium.com/the-effective-cissp/multi-factor-authentication-mfa-c30808f81a57",
        "Medium / The Effective CISSP: Multi-Factor Authentication (Wentz Wu)",
        "MFA explanation by Wentz Wu."),
    src("https://www.isc2.org/Insights/2023/10/Cybersecurity-Awareness-Month-Multifactor-Authentication",
        "ISC2 Insights: MFA — Enhancing Digital Security",
        "Official ISC2 perspective on MFA."),
    src("https://community.isc2.org/t5/Tech-Talk/Is-this-really-MFA/td-p/20087",
        "ISC2 Community: Is this really MFA?",
        "Member discussion of MFA edge cases."),
    src("https://thorteaches.com/glossary/just-in-time-jit-access/",
        "ThorTeaches: Just-in-Time (JIT) access glossary",
        "Glossary entry for JIT access from Thor Pedersen."),
    src("https://delinea.com/what-is/just-in-time-access",
        "Delinea: What is Just-in-Time (JIT) Access?",
        "Vendor explainer of JIT privilege management."),
    src("https://hoop.dev/blog/unlocking-the-power-of-just-in-time-provisioning-for-mfa-a-technology-managers-guide/",
        "hoop.dev: JIT Provisioning for MFA — A Technology Manager's Guide",
        "Manager-level JIT + MFA integration guide."),
    src("https://hoop.dev/blog/unlocking-security-just-in-time-provisioning-with-multi-factor-authentication",
        "hoop.dev: Just-in-Time Provisioning with MFA",
        "Practical implementation patterns for JIT + MFA."),
    src("https://www.cyberark.com/what-is/just-in-time-access/",
        "CyberArk: What is Just-In-Time Access?",
        "Vendor reference on JIT access for privileged accounts."),
    src("https://csrc.nist.gov/pubs/sp/800/63/3/final",
        "NIST SP 800-63-3: Digital Identity Guidelines",
        "Authoritative AAL/IAL/FAL identity assurance levels."),
    src("https://datatracker.ietf.org/doc/html/rfc6749",
        "RFC 6749: The OAuth 2.0 Authorization Framework",
        "OAuth 2.0 base specification."),
    src("https://openid.net/developers/specs/",
        "OpenID Connect: Core Specifications",
        "OIDC core specifications and ID token format."),
    src("https://datatracker.ietf.org/doc/html/rfc4120",
        "RFC 4120: The Kerberos Network Authentication Service (V5)",
        "Kerberos V5 authoritative reference."),
]

# Domain 6: Security Assessment & Testing (12%)
D6 = [
    src("https://destcert.com/resources/cissp-domain-6-security-assessment-and-testing/",
        "DestCert: CISSP Domain 6 — Security Assessment & Testing",
        "Domain 6 (12%) covering test strategies, audits, KPIs."),
    src("https://blog.balancedsec.com/p/understanding-cissp-domain-6-security",
        "BalancedSec: Understanding CISSP Domain 6 — Part 1",
        "Domain 6 study notes."),
    src("https://certifiedcissp.com/domain-6-security-assessment/",
        "CertifiedCISSP: Domain 6 — Security Assessment and Testing",
        "Free Domain 6 notes."),
    src("https://medium.com/@sharma1997pushpak/cissp-domain-6-security-assessment-and-testing-26fb61230c43",
        "Medium / Pushpak Sharma: CISSP Domain 6",
        "Personal study writeup of Domain 6."),
    src("https://quizlet.com/217188152/cissp-practice-tests-chapter-6-security-assessment-and-testing-domain-6-flash-cards/",
        "Quizlet: CISSP Practice Tests Chapter 6",
        "Flashcards aligned to chapter 6 of the official practice tests."),
    src("https://flashgenius.net/blog-article/cissp-practice-questions-security-assessment-and-testing-1749432273613",
        "FlashGenius: Free CISSP Practice Questions Domain 6 (2025)",
        "Updated 2025 Domain 6 free practice questions."),
    src("https://siteforinfotech.com/2025/11/cissp-domain-6-practice-test-the-best-way-to-enhance-your-skills.html",
        "InfoTechSite: CISSP Domain 6 Practice Test",
        "Sample Domain 6 practice questions."),
    src("https://cissprep.net/domain-6-security-assessment-and-testing/",
        "CISSPrep: Domain 6 — Security Assessment and Testing",
        "Free Domain 6 study notes."),
    src("https://quizlet.com/819400399/cissp-domain-6-security-assessment-and-testing-flash-cards/",
        "Quizlet: CISSP Domain 6 Security Assessment flashcards",
        "Updated card deck for Domain 6."),
    src("https://cybermind.in/cissp/cissp-domain-6-security-assessment-and-testing/",
        "CyberMind: CISSP Domain 6 — Free Quizzes",
        "Free Domain 6 quiz set."),
    src("https://www.infosectrain.com/blog/black-box-vs-white-box-vs-grey-box-penetration-testing",
        "InfosecTrain: Black Box vs White Box vs Grey Box Penetration Testing",
        "Comparison of pen-test box approaches."),
    src("https://www.tracesecurity.com/blog/articles/what-is-black-box-white-box-and-gray-box-testing/",
        "TraceSecurity: What is Black/White/Gray Box Testing?",
        "Explainer of testing box types."),
    src("https://www.infosecinstitute.com/resources/penetration-testing/what-are-black-box-grey-box-and-white-box-penetration-testing/",
        "Infosec Institute: Black/Grey/White Box Pen Testing",
        "Pen-test box types overview."),
    src("https://www.eccouncil.org/cybersecurity-exchange/penetration-testing/black-box-gray-box-and-white-box-penetration-testing-importance-and-uses/",
        "EC-Council: Black, Gray, and White-Box Penetration Testing",
        "Pen-test box overview from EC-Council."),
    src("https://www.pentesting.org/cissp-study-guide/",
        "PenTesting.org: CISSP Study Guide",
        "Pen-testing-focused CISSP study guide."),
    src("https://www.cbtnuggets.com/blog/technology/networking/what-is-black-vs-gray-vs-white-box-testing",
        "CBT Nuggets: What is Pen Testing? Black/Grey/White box.",
        "Plain-language pen-testing primer."),
    src("https://deepstrike.io/blog/black-box-vs-white-box-testing",
        "DeepStrike: Black Box vs White Box Penetration Testing — 2026 Guide",
        "Updated pen-test types reference."),
    src("https://bsg.tech/blog/black-box-vs-white-box-vs-grey-box-penetration-testing/",
        "BSG: Black/White/Grey Box Pentest",
        "Pen-test box explainer."),
    src("https://cybersecurity.bureauveritas.com/services/information-technology/pentesting-services/pentesting-methods/black-gray-crystal-pentesting-boxes",
        "Bureau Veritas: Pentest Boxes — Black, Grey, Crystal, White",
        "Adds 'crystal box' (full transparency) to typology."),
    src("https://www.cobalt.io/blog/black-gray-and-white-box-pentests",
        "Cobalt: Decoding the Differences — Black, Gray, and White-Box Pentests",
        "Practical pen-test type comparison."),
    src("https://socreports.com/white-papers/educational/isae-3402-type-2-reports",
        "SOCReports: ISAE 3402 Type 2 Reports — SOC 2 Audits",
        "Distinguishes ISAE 3402 from SOC 2."),
    src("https://brandcompliance.com/en/docs/soc-2-or-isae-3402/",
        "BrandCompliance: SOC 2 or ISAE 3402?",
        "Decision guidance for picking the right audit standard."),
    src("https://www.networking4all.com/en/support/faq/what-is-isae-3402",
        "Networking4all: What is ISAE 3402?",
        "ISAE 3402 FAQ."),
    src("https://www.zluri.com/blog/isae-3402-vs-soc-2",
        "Zluri: ISAE 3402 vs SOC 2",
        "Comparison of audit frameworks."),
    src("https://en.wikipedia.org/wiki/ISAE_3402",
        "Wikipedia: ISAE 3402",
        "Encyclopedia overview of ISAE 3402."),
    src("https://www.cgcompliance.com/services/audits-and-assessment/isae-3402",
        "CG Compliance: ISAE 3402 Readiness Assessment Audit",
        "Audit firm description of ISAE 3402."),
    src("https://www.certicus.com/isae-3402",
        "Certicus: ISAE 3402 / SOC 1",
        "ISAE 3402 audit firm overview."),
    src("https://securance.com/news/isae-3402-soc-1-type-i-vs-type-ii",
        "Securance: ISAE 3402 / SOC 1 Type I vs Type II",
        "Type I vs Type II audit distinction."),
    src("https://www.crowe.com/id/insights/a-guide-to-iso-27001-isae-3000-3402-and-soc",
        "Crowe: Guide to ISO 27001, ISAE 3000/3402, and SOC",
        "Maps ISO 27001 against ISAE/SOC frameworks."),
    src("https://www.futura.international/corporate-it-digital-and-cybersecurity-audit-governance-services/soc-1-audit-isae-3402-and-ssae-18-and-soc-2-audit-isae-3000-tsp-100-trust-principles-criteria/",
        "Futura: SOC 1/ISAE 3402/SSAE 18 + SOC 2/ISAE 3000",
        "Map of audit standards globally."),
    src("https://csrc.nist.gov/pubs/sp/800/115/final",
        "NIST SP 800-115: Technical Guide to Information Security Testing and Assessment",
        "Authoritative NIST reference for security testing methodology."),
    src("https://owasp.org/www-project-web-security-testing-guide/",
        "OWASP Web Security Testing Guide (WSTG)",
        "OWASP authoritative web testing guide."),
]

# Domain 7: Security Operations (13%)
D7 = [
    src("https://destcert.com/resources/cissp-domain-7-security-operations/",
        "DestCert: Insights into CISSP Domain 7 — Security Operations",
        "Domain 7 (13%) IR, forensics, BCP/DRP."),
    src("https://siteforinfotech.com/2026/02/cissp-domain-7-practice-test.html",
        "InfoTechSite: CISSP Domain 7 Practice Test",
        "Domain 7 practice question set."),
    src("https://www.crusec.com/single-post/2019/07/08/crusec-s-2019-cissp-study-guide-domain-7-security-operations",
        "CruSec: 2019 CISSP Study Guide — Domain 7",
        "Domain 7 long-form study guide."),
    src("https://wentzwu.com/2020/05/13/cissp-practice-questions-20200514/",
        "Wentz Wu: CISSP Practice Questions 20200514",
        "Operations and IR question set."),
    src("https://www.linkedin.com/pulse/cissp-domain-7-security-operations-part-1-understand-soundararajan",
        "LinkedIn (Soundararajan): CISSP Domain 7 — Investigations",
        "LinkedIn article on investigations and forensics."),
    src("https://quizlet.com/218032748/cissp-domain-7-security-operations-investigations-flash-cards/",
        "Quizlet: CISSP Domain 7 Security Operations — Investigations",
        "Investigations flashcards."),
    src("https://www.coursera.org/learn/cissp-domain-7-security-operations",
        "Coursera: CISSP Domain 7 Security Operations",
        "Coursera course on Domain 7."),
    src("https://cdn.comparitech.com/wp-content/uploads/2020/01/CISSP-Cheat-Sheet-Domain-7.pdf",
        "Comparitech: CISSP Cheat Sheet Domain 7",
        "Compact cheat sheet for Domain 7."),
    src("https://intrinsecsecurity.com/blog/training-certifications/20-questions-cissp-edition/",
        "Intrinsec Security: 20 Questions — CISSP Edition",
        "Sample CISSP questions including Domain 7 topics."),
    src("https://quizlet.com/74996233/cissp-test-questions-domain-7-security-operations-flash-cards/",
        "Quizlet: CISSP Test Questions Domain 7",
        "Domain 7 flashcards."),
    src("https://www.klogixsecurity.com/blog/navigating-incident-response-a-deep-dive-into-nist-800-61-containment-eradication-and-recovery",
        "K Logix: Navigating IR — NIST 800-61 Containment, Eradication, Recovery",
        "Deep dive into NIST 800-61 IR phases."),
    src("https://csrc.nist.gov/files/pubs/sp/800/61/r2/final/docs/draft-sp800-61rev2.pdf",
        "NIST SP 800-61 Rev 2 (PDF)",
        "Authoritative IR lifecycle reference."),
    src("https://nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-61r2.pdf",
        "NIST SP 800-61 Rev 2 (NVLPubs PDF)",
        "Same NIST 800-61r2 published copy."),
    src("https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-61r3.pdf",
        "NIST SP 800-61 Rev 3 PDF",
        "Updated IR guidance with continuous improvement focus."),
    src("https://armorpoint.com/2024/05/08/a-step-by-step-guide-to-incident-response-practical-guidance-from-nist-sp-800-61/",
        "ArmorPoint: Step-by-Step Guide to IR — NIST SP 800-61",
        "Practical IR walkthrough."),
    src("https://flashgenius.net/guides/incident-response-for-cissp-2026-nist-800-61-phases-evidence-handling-amp-chain-of-custody-interactive-study-guide",
        "FlashGenius: IR for CISSP 2026 — NIST 800-61 + chain of custody",
        "Interactive 2026 study guide for IR."),
    src("https://tandem.app/blog/updated-nist-incident-response-guidance-sp-800-61-rev-3",
        "Tandem: Updated NIST IR Guidance — SP 800-61 Rev 3",
        "Summary of changes in 800-61 Rev 3."),
    src("https://medium.com/@bhavin200/nist-incident-response-800-61-a-comprehensive-guide-to-the-four-phase-lifecycle-for-identifying-3c79b9b0a993",
        "Medium / Bhavin: NIST IR 800-61 — Comprehensive Guide",
        "Four-phase IR lifecycle walkthrough."),
    src("https://medium.com/@divyesh.vaishanv/nist-sp-800-61-incident-response-life-cycle-explained-b7b63372cd3c",
        "Medium / Divyesh: NIST SP 800-61 IR Life Cycle Explained",
        "IR lifecycle explainer."),
    src("https://www.rapid7.com/blog/post/2017/01/11/introduction-to-incident-response-life-cycle-of-nist-sp-800-61/",
        "Rapid7: Introduction to IR Life Cycle of NIST SP 800-61",
        "Vendor IR lifecycle introduction."),
    src("https://cissprep.net/data-backup/",
        "CISSPrep: Data Backup",
        "Backup types (full, incremental, differential) and 3-2-1 rule."),
    src("https://www.pearsonitcertification.com/articles/article.aspx?p=1329710&seqNum=3",
        "Pearson: CISSP Exam Cram — BC/DR Planning",
        "BCP/DRP exam-cram article."),
    src("https://www.cybrary.it/blog/disaster-recovery-hot-cold-warm-sites",
        "Cybrary: CISSP — Hot, Cold, and Warm Sites",
        "Recovery site types comparison."),
    src("https://www.infosecinstitute.com/resources/retired/cissp-domain-business-continuity-and-disaster-recovery/",
        "Infosec Institute: CISSP Domain — BC/DR",
        "BC/DR review article."),
    src("https://www.examcollection.com/blog/mastering-disaster-recovery-for-cissp-hot-cold-and-warm-site-strategies/",
        "ExamCollection: Mastering DR for CISSP",
        "DR site strategy discussion."),
    src("https://destcert.com/resources/recovery-strategies-mindmap-cissp-domain-7/",
        "DestCert: Recovery Strategies Mindmap — Domain 7",
        "Recovery strategies mind map."),
    src("https://quizlet.com/469536675/cissp-7-backupsredundancy-flash-cards/",
        "Quizlet: CISSP 7 — Backups & Redundancy",
        "Backup/redundancy flashcards."),
    src("https://www.examguides.com/Networkplus/network-plus-15.htm",
        "ExamGuides: Disaster Recovery Concepts",
        "DR concepts (cross-cert) used by some CISSP candidates."),
    src("https://www.omnisecu.com/ccna-security/types-of-backup-sites.php",
        "OmniSecu: Types of Backup Sites",
        "Hot/warm/cold/mobile site types."),
    src("https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/4/html/introduction_to_system_administration/s2-disaster-recovery-sites",
        "Red Hat Docs: Backup Sites — Cold, Warm, Hot",
        "Vendor doc on DR site types."),
    src("https://csrc.nist.gov/pubs/sp/800/34/r1/final",
        "NIST SP 800-34 Rev 1: Contingency Planning Guide",
        "Authoritative NIST CP/BC/DR guide."),
    src("https://www.cisa.gov/sites/default/files/publications/Critical_Infrastructure_Operations_Center_Best_Practices_FINAL_v1_508.pdf",
        "CISA: Operations Center Best Practices",
        "Government SOC best-practice reference."),
]

# Domain 8: Software Development Security (10%)
D8 = [
    src("https://destcert.com/resources/cissp-domain-8-software-development-security/",
        "DestCert: CISSP Domain 8 — Software Development Security Guide 2025",
        "Domain 8 (10%) walkthrough."),
    src("https://siteforinfotech.com/2026/02/cissp-domain-8-practice-test.html",
        "InfoTechSite: CISSP Domain 8 Practice Test",
        "Domain 8 practice questions."),
    src("https://trainingcamp.com/webinars/cissp-software-security-owasp-secure-sdlc-devsecops/",
        "TrainingCamp: CISSP Software Security — OWASP, Secure SDLC, DevSecOps",
        "Webinar on Domain 8 topics."),
    src("https://lognpacific.com/free-certification-practice-tests/free-cissp-practice-questions/cissp-domain-8-software-development-security-domain-8-cissp-exam/",
        "LognPacific: Free CISSP Domain 8 Practice Questions",
        "Domain 8 free practice question set."),
    src("https://blog.balancedsec.com/p/understanding-cissp-domain-8-software",
        "BalancedSec: Understanding CISSP Domain 8 — Part 1",
        "Domain 8 study notes."),
    src("https://mappedarch.medium.com/cissp-domain-8-software-development-security-2ca041c0c03a",
        "Medium (Nityananda): CISSP Domain 8",
        "Domain 8 explained for exam and real-world application."),
    src("https://www.threatonthewire.com/cissp-domain-8-secure-coding-foundations/",
        "ThreatOnTheWire: Secure Coding Foundations for Managers",
        "Manager-level secure coding overview."),
    src("https://cissprep.net/domain-8-software-development-security/",
        "CISSPrep: Domain 8 — Software Development Security",
        "Free Domain 8 study notes."),
    src("https://www.coursera.org/learn/cissp-domain-8-software-dev-security",
        "Coursera: CISSP Domain 8 — Software development security",
        "Coursera course on Domain 8."),
    src("https://www.techtarget.com/searchsecurity/quiz/Domain-8-Security-in-software-development-lifecycle-quiz",
        "TechTarget: Domain 8 — Security in SDLC quiz",
        "SDLC security quiz."),
    src("https://owasp.org/Top10/A11_2021-Next_Steps/",
        "OWASP Top 10:2021 — Next Steps",
        "OWASP Top 10 next-steps reference."),
    src("https://cqr.company/web-vulnerabilities/time-of-check-to-time-of-use-tocttou-race-conditions/",
        "CQR: TOCTTOU Race Conditions",
        "Practical TOCTOU vulnerability explainer."),
    src("https://destcert.com/resources/vulnerabilities-in-systems-mindmap-cissp-domain-3/",
        "DestCert: Vulnerabilities in Systems MindMap (cross-domain)",
        "Mind-map covering injection, race conditions, buffer overflow."),
    src("https://www.youtube.com/watch?v=Uta6M9PMXZo",
        "YouTube: Exploit TOCTOU Race Condition Vulnerabilities",
        "Hands-on TOCTOU exploitation walkthrough."),
    src("https://ahmed-tarek.gitbook.io/security-notes/owsap-top-10-2025/a06-insecure-design/race-conditions",
        "Ahmed Tarek (GitBook): Race Conditions — OWASP Top 10 2025",
        "OWASP A06 Insecure Design race-condition examples."),
    src("https://cwe.mitre.org/data/definitions/367.html",
        "CWE-367: Time-of-check Time-of-use (TOCTOU)",
        "MITRE CWE entry for TOCTOU."),
    src("https://resources.infosecinstitute.com/topic/race-condition-toctou-vulnerability-lab/",
        "Infosec Institute: Race condition (TOCTOU) vulnerability lab",
        "Hands-on TOCTOU lab."),
    src("https://book.jorianwoltjer.com/binary-exploitation/race-conditions",
        "Practical CTF: Race Conditions",
        "CTF-oriented race condition writeup."),
    src("https://owasp.org/www-community/vulnerabilities/Buffer_Overflow",
        "OWASP: Buffer Overflow",
        "OWASP authoritative buffer overflow reference."),
    src("https://cqr.company/web-vulnerabilities/race-condition-vulnerability/",
        "CQR: Race condition vulnerability",
        "Practical race condition explainer."),
    src("https://www.aikido.dev/learn/compliance/compliance-frameworks/nist-ssdf",
        "Aikido: NIST SSDF (SP 800-218) Secure Software Development Explained",
        "SSDF practices integrated into Agile, CI/CD, DevOps."),
    src("https://cissp.jpmck.com/domains/8/",
        "Jim's CISSP Notes: Domain 8 — Software Development Security",
        "Notes on Domain 8 from Jim McKenna."),
    src("https://info-savvy.com/cissp-maturity-models-bk1d8t1st2p2/",
        "Info-Savvy: CISSP Maturity Models",
        "CMM, SAMM, BSIMM comparison."),
    src("https://onlinelibrary.wiley.com/doi/full/10.1002/smr.2711",
        "Wiley: Evolution of secure development lifecycles & maturity models",
        "Academic review of SDL/SAMM/BSIMM evolution."),
    src("https://www.practical-devsecops.com/devsecops-maturity-model-dsomm/",
        "Practical DevSecOps: DevSecOps Maturity Model (DSOMM)",
        "DSOMM framework for DevSecOps maturity."),
    src("https://www.infosecinstitute.com/resources/application-security/software-maturity-models-for-appsec-initiatives/",
        "Infosec Institute: Software maturity models for AppSec",
        "AppSec maturity model overview."),
    src("https://wentzwu.com/2021/10/22/cissp-practice-questions-20211022/",
        "Wentz Wu: CISSP Practice Questions 20211022",
        "Domain 8 question set."),
    src("https://www.practical-devsecops.com/wp-content/uploads/2024/06/eBook-Integrating-Security-into-CI_CD-Pipelines-through-DevSecOps-Approach-1.pdf",
        "Practical DevSecOps: Integrating Security into CI/CD Pipelines",
        "Free eBook on DevSecOps CI/CD integration."),
    src("https://github.com/OWASP/DevSecOpsGuideline",
        "GitHub: OWASP DevSecOps Guideline",
        "OWASP-maintained DevSecOps reference."),
    src("https://csrc.nist.gov/pubs/sp/800/218/final",
        "NIST SP 800-218: Secure Software Development Framework (SSDF)",
        "Authoritative SSDF reference for Domain 8."),
    src("https://owasp.org/www-project-application-security-verification-standard/",
        "OWASP: Application Security Verification Standard (ASVS)",
        "ASVS verification levels for app security."),
    src("https://owasp.org/www-project-samm/",
        "OWASP: Software Assurance Maturity Model (SAMM)",
        "SAMM authoritative project page."),
]


def main() -> None:
    payload = {
        "captured": CAPTURED,
        "method": "main-thread WebSearch + WebFetch (subagent web tools were denied)",
        "domains": {
            1: {"name": "Security and Risk Management", "weight_pct": 16, "sources": D1},
            2: {"name": "Asset Security", "weight_pct": 10, "sources": D2},
            3: {"name": "Security Architecture and Engineering", "weight_pct": 13, "sources": D3},
            4: {"name": "Communication and Network Security", "weight_pct": 13, "sources": D4},
            5: {"name": "Identity and Access Management", "weight_pct": 13, "sources": D5},
            6: {"name": "Security Assessment and Testing", "weight_pct": 12, "sources": D6},
            7: {"name": "Security Operations", "weight_pct": 13, "sources": D7},
            8: {"name": "Software Development Security", "weight_pct": 10, "sources": D8},
        },
    }
    OUT.write_text(json.dumps(payload, indent=2))
    print(f"[+] {OUT} ({OUT.stat().st_size/1024:.1f} KiB)")
    total = 0
    for d_id, d in payload["domains"].items():
        n = len(d["sources"])
        total += n
        flag = "OK" if n >= 30 else "LOW"
        print(f"  D{d_id} {d['name']:<42}  {n:3d} sources  [{flag}]")
    print(f"  total: {total} sources")


if __name__ == "__main__":
    main()
