#!/usr/bin/env python3
"""Build flashcards.json with ~200 high-yield CISSP cards.

Each card has term, definition (paraphrased), domain, source, source_ref.
SM-2 state (easiness, interval, repetitions, due) is maintained at runtime.
"""
import json
from pathlib import Path

ROOT = Path("/Users/mike/cissp")
OUT = ROOT / "flashcards.json"
WEB = json.loads((ROOT / "web_research.json").read_text())


def _web_url(domain: int, needle: str) -> str:
    for s in WEB["domains"][str(domain)]["sources"]:
        if needle in s["url"]:
            return s["url"]
    return ""


def C(cid, domain, term, back, source="canonical",
      guide_pages=None, web_url=None, tags=None):
    return {
        "id": cid,
        "domain": domain,
        "term": term,
        "back": back,
        "source": source,
        "guide_pages": guide_pages or [],
        "web_url": web_url or "",
        "tags": tags or [],
    }


CARDS: list[dict] = []

# Domain 1
CARDS += [
    C("F1-001", 1, "CIA Triad",
      "Confidentiality, Integrity, Availability — the three core security objectives.",
      source="guide", guide_pages=[150, 152]),
    C("F1-002", 1, "DAD Triad",
      "Disclosure, Alteration, Destruction — the negative inverse of CIA used to frame threats.",
      source="canonical"),
    C("F1-003", 1, "Parkerian Hexad",
      "Confidentiality, Possession/Control, Integrity, Authenticity, Availability, Utility — six-attribute model expanding on CIA.",
      source="canonical"),
    C("F1-004", 1, "Due Care",
      "Taking the actions a reasonable person would take to protect the organisation (the 'doing').",
      source="guide", guide_pages=[180, 184]),
    C("F1-005", 1, "Due Diligence",
      "Ongoing investigation, validation, and verification that controls remain appropriate (the 'homework').",
      source="guide", guide_pages=[180, 184]),
    C("F1-006", 1, "ALE Formula",
      "ALE = SLE × ARO. Single Loss Expectancy times Annualised Rate of Occurrence.",
      source="guide", guide_pages=[300, 305]),
    C("F1-007", 1, "SLE Formula",
      "SLE = AV × EF. Asset Value times Exposure Factor (the percentage of loss).",
      source="guide", guide_pages=[300, 305]),
    C("F1-008", 1, "Risk Treatment Options",
      "Mitigate, Avoid, Transfer (share), Accept — the four risk responses.",
      source="guide", guide_pages=[310, 314]),
    C("F1-009", 1, "Inherent vs Residual Risk",
      "Inherent = risk before controls. Residual = risk remaining after controls. Secondary = risk introduced by a control.",
      source="canonical"),
    C("F1-010", 1, "STRIDE",
      "Spoofing, Tampering, Repudiation, Information Disclosure, Denial of Service, Elevation of Privilege — Microsoft's threat-categorisation model.",
      source="web",
      web_url=_web_url(1, "destcert.com/resources/threat-modeling")),
    C("F1-011", 1, "DREAD",
      "Damage, Reproducibility, Exploitability, Affected users, Discoverability — threat-severity scoring (often paired with STRIDE).",
      source="web",
      web_url=_web_url(1, "softwaresecured.com/post/comparison-of-stride")),
    C("F1-012", 1, "PASTA",
      "Process for Attack Simulation and Threat Analysis — a 7-stage, risk-centric, attacker-focused threat-modeling methodology.",
      source="web",
      web_url=_web_url(1, "destcert.com/resources/threat-modeling")),
    C("F1-013", 1, "VAST",
      "Visual, Agile, Simple Threat — produces both an application threat model and an operational threat model.",
      source="canonical"),
    C("F1-014", 1, "ISC2 Code of Ethics — Canon Ordering",
      "(1) Protect society, common good, public trust, infrastructure; (2) Act honourably; (3) Provide diligent service; (4) Advance the profession.",
      source="web",
      web_url=_web_url(1, "isc2.org/Ethics")),
    C("F1-015", 1, "BIA Time Metrics",
      "MTD = max tolerable downtime; RTO = recovery time objective; RPO = recovery point objective; WRT = work recovery time. RTO + WRT ≤ MTD.",
      source="web",
      web_url=_web_url(1, "wentzwu.com/2020/04/05/common-bia")),
    C("F1-016", 1, "GDPR Roles",
      "Controller (decides purpose/means), Processor (acts on instructions), DPO (compliance/oversight), Data Subject (the individual).",
      source="web",
      web_url=_web_url(1, "gdpr-info.eu")),
    C("F1-017", 1, "GDPR Fines (Higher Tier)",
      "Up to €20 million or 4% of global annual turnover (whichever is higher) for serious violations of the regulation.",
      source="web",
      web_url=_web_url(1, "gdpr-info.eu")),
    C("F1-018", 1, "NIST CSF 2.0 Functions",
      "Govern, Identify, Protect, Detect, Respond, Recover (Govern was added in 2.0).",
      source="web",
      web_url=_web_url(1, "nist.gov/cyberframework")),
    C("F1-019", 1, "NIST RMF Steps",
      "Categorise → Select → Implement → Assess → Authorise → Monitor (NIST SP 800-37).",
      source="web",
      web_url=_web_url(1, "csrc.nist.gov/pubs/sp/800/37")),
    C("F1-020", 1, "PCI-DSS",
      "Payment Card Industry Data Security Standard — contractual (not statutory) framework protecting cardholder data; v4.0 mandatory March 31, 2025.",
      source="canonical"),
    C("F1-021", 1, "SOX",
      "Sarbanes-Oxley Act (2002) — internal controls over financial reporting for US public companies; CEO/CFO attestations.",
      source="canonical"),
    C("F1-022", 1, "ISO 27001 vs 27002",
      "27001 = ISMS requirements (auditable); 27002 = control catalog/guidance.",
      source="web",
      web_url=_web_url(1, "iso.org/standard/27001")),
    C("F1-023", 1, "Three Lines Model (IIA)",
      "1st: operational management; 2nd: risk/compliance; 3rd: internal audit reporting to the board.",
      source="canonical"),
    C("F1-024", 1, "Mandatory Vacation",
      "Force absence so a substitute can detect ongoing fraud or unsafe practices that depend on continuous control by one person.",
      source="guide", guide_pages=[290, 293]),
    C("F1-025", 1, "Separation of Duties (SoD)",
      "Split sensitive workflows so no single person can complete them; requires collusion to commit fraud.",
      source="guide", guide_pages=[290, 295]),
    C("F1-026", 1, "Recovery Sites — RTO Order",
      "Hot (minutes/hours) → Warm (~12 hours) → Cold (days) → Mobile (variable) → Reciprocal (variable).",
      source="canonical"),
    C("F1-027", 1, "DR Test Types — Disruption Order",
      "Tabletop → Walkthrough → Simulation → Parallel → Full Interruption (least → most disruptive).",
      source="canonical"),
    C("F1-028", 1, "Risk Register Entry",
      "A documented risk = (threat × vulnerability × impact) with likelihood, owner, treatment, status.",
      source="canonical"),
    C("F1-029", 1, "Quantitative vs Qualitative Risk",
      "Quantitative uses numbers (ALE, SLE, ARO) for cost-benefit; qualitative uses ratings (high/med/low) and captures intangibles.",
      source="canonical"),
    C("F1-030", 1, "Documentation Hierarchy",
      "Policy (mandatory intent) → Standard (mandatory specifics) → Procedure (steps) → Guideline (recommendations).",
      source="guide", guide_pages=[183, 188]),
]

# Domain 2
CARDS += [
    C("F2-001", 2, "Data Owner",
      "Senior business leader accountable for classification and decisions about data use, protection, and destruction.",
      source="guide", guide_pages=[600, 605]),
    C("F2-002", 2, "Data Custodian",
      "Operational role implementing controls per owner's direction (backups, restores, ACL maintenance).",
      source="guide", guide_pages=[605, 608]),
    C("F2-003", 2, "Data Steward",
      "SME-style role responsible for data quality, metadata, and definitions across an organisation.",
      source="canonical"),
    C("F2-004", 2, "Data Processor (GDPR)",
      "An entity that processes personal data on behalf of the controller, per controller instructions.",
      source="web",
      web_url=_web_url(2, "gdpr-info.eu")),
    C("F2-005", 2, "Data States",
      "At rest, In transit, In use — each requires distinct protections (encryption, TLS, confidential computing).",
      source="canonical"),
    C("F2-006", 2, "NIST 800-88 Sanitisation",
      "Clear (overwrite, in-house), Purge (degauss/crypto-erase, leaves control), Destroy (shred/incinerate, highest impact).",
      source="web",
      web_url=_web_url(2, "csrc.nist.gov/pubs/sp/800/88/r1")),
    C("F2-007", 2, "Cryptographic Erase",
      "Destroy/replace the media-encryption key on self-encrypting drives — instantly invalidates ciphertext WITHOUT touching every block.",
      source="web",
      web_url=_web_url(2, "inventivehq.com/blog/nist-800-88")),
    C("F2-008", 2, "Degaussing",
      "Strong magnetic field that randomises magnetic domains — works on HDDs and tapes only (not SSDs).",
      source="canonical"),
    C("F2-009", 2, "Scoping vs Tailoring",
      "Scoping REMOVES irrelevant controls. Tailoring MODIFIES remaining controls (parameters, compensating).",
      source="web",
      web_url=_web_url(2, "destcert.com/resources/scoping-tailoring")),
    C("F2-010", 2, "FIPS 199 Categorisation",
      "Low / Moderate / High impact based on confidentiality, integrity, and availability — high-water mark per dimension.",
      source="web",
      web_url=_web_url(2, "csrc.nist.gov/pubs/fips/199")),
    C("F2-011", 2, "Tokenisation vs Encryption",
      "Tokenisation = substitute surrogate values, reversibility via vault. Encryption = mathematically reversible with key.",
      source="canonical"),
    C("F2-012", 2, "Anonymisation vs Pseudonymisation (GDPR)",
      "Anonymisation = irreversible, removes from GDPR scope. Pseudonymisation = reversible with separately stored key, still personal data.",
      source="web",
      web_url=_web_url(2, "gdpr-info.eu")),
    C("F2-013", 2, "Data Lifecycle",
      "Create → Store → Use → Share → Archive → Destroy.",
      source="canonical"),
    C("F2-014", 2, "DLP",
      "Data Loss Prevention: detect/block sensitive data leaving authorised locations (network, endpoint, storage, email).",
      source="canonical"),
    C("F2-015", 2, "Government Classification Levels",
      "Confidential (damage), Secret (serious damage), Top Secret (exceptionally grave damage); FOUO is a control marking.",
      source="canonical"),
    C("F2-016", 2, "Commercial Classification (Common)",
      "Public → Internal/Sensitive → Confidential → Restricted (4 tiers is generally optimal).",
      source="canonical"),
    C("F2-017", 2, "PII vs PHI",
      "PII = personally identifiable information (broad). PHI = HIPAA-defined protected health information (subset, healthcare context).",
      source="canonical"),
    C("F2-018", 2, "GDPR Article 17",
      "Right to erasure ('right to be forgotten') — controllers must delete personal data on request unless an exemption applies.",
      source="web",
      web_url=_web_url(2, "gdpr-info.eu")),
    C("F2-019", 2, "GDPR Article 6 Lawful Bases",
      "Consent, Contract, Legal obligation, Vital interest, Public task, Legitimate interest. One of these must be cited for any processing.",
      source="web",
      web_url=_web_url(2, "gdpr-info.eu")),
    C("F2-020", 2, "EOL vs EOS",
      "End-of-Life: vendor stops selling. End-of-Support: vendor stops patching — major security risk.",
      source="canonical"),
]

# Domain 3
CARDS += [
    C("F3-001", 3, "Bell-LaPadula",
      "Confidentiality model: NO READ UP, NO WRITE DOWN. Lattice-based, supports trusted subjects.",
      source="guide", guide_pages=[745, 752]),
    C("F3-002", 3, "Biba",
      "Integrity model: NO READ DOWN, NO WRITE UP. Inverse of Bell-LaPadula.",
      source="guide", guide_pages=[753, 758]),
    C("F3-003", 3, "Clark-Wilson",
      "Integrity via well-formed transactions: subjects → TPs (transformation procedures) → CDIs/UDIs (constrained/unconstrained data items); IVPs verify integrity.",
      source="guide", guide_pages=[755, 760]),
    C("F3-004", 3, "Brewer-Nash (Chinese Wall)",
      "Dynamic conflict-of-interest model — restricts access based on prior access history.",
      source="guide", guide_pages=[760, 763]),
    C("F3-005", 3, "Take-Grant",
      "Models how rights can propagate between subjects via 'take' and 'grant' operations.",
      source="guide", guide_pages=[761, 764]),
    C("F3-006", 3, "Graham-Denning",
      "Eight rules for creating/deleting subjects, objects, and rights in a protection system.",
      source="canonical"),
    C("F3-007", 3, "Reference Monitor",
      "Always invoked, tamper-proof, small enough to be analysed/tested. Implemented by the security kernel.",
      source="guide", guide_pages=[796, 800]),
    C("F3-008", 3, "TCB",
      "Trusted Computing Base — hardware/software/firmware whose correctness is essential to security policy enforcement.",
      source="guide", guide_pages=[795, 800]),
    C("F3-009", 3, "Common Criteria EAL",
      "Evaluation Assurance Level (EAL1 functionally tested → EAL7 formally verified). Measures evaluation rigor, NOT inherent security.",
      source="web",
      web_url=_web_url(3, "commoncriteriaportal.org/cc")),
    C("F3-010", 3, "FIPS 140-3",
      "Federal validation standard for cryptographic modules; four levels; references ISO/IEC 19790:2012.",
      source="web",
      web_url=_web_url(3, "csrc.nist.gov/pubs/fips/140/3")),
    C("F3-011", 3, "AES Modes",
      "ECB (insecure-deterministic), CBC (chaining, no integrity), CTR (stream-like), GCM (AEAD: confidentiality + integrity).",
      source="web",
      web_url=_web_url(3, "destcert.com/resources/types-of-ciphers")),
    C("F3-012", 3, "Symmetric vs Asymmetric Cryptography",
      "Symmetric: shared key (fast, key distribution problem). Asymmetric: keypair (slower, solves distribution; identity binding via PKI).",
      source="canonical"),
    C("F3-013", 3, "Hash Properties",
      "One-way (irreversible), collision-resistant, fixed-length output, deterministic. Examples: SHA-256, SHA-3.",
      source="guide", guide_pages=[862, 866]),
    C("F3-014", 3, "Digital Signature",
      "Hash + private-key encryption. Provides integrity + authenticity + non-repudiation. MACs lack non-repudiation.",
      source="guide", guide_pages=[870, 875]),
    C("F3-015", 3, "PKI Components",
      "CA (issues), RA (registers), CRL/OCSP (revokes), repository (stores). Hierarchical or web-of-trust.",
      source="canonical"),
    C("F3-016", 3, "TPM",
      "Trusted Platform Module — chip on the motherboard providing root of trust for measurement, sealed storage, attestation.",
      source="web",
      web_url=_web_url(3, "wolfssl.com/difference-hsm-tpm-secure-enclave")),
    C("F3-017", 3, "HSM",
      "Hardware Security Module — tamper-resistant appliance for high-volume key generation, storage, and crypto operations.",
      source="canonical"),
    C("F3-018", 3, "Side-Channel Attack",
      "Recover secrets from observable physical phenomena (power, EM, timing, acoustic) during processing.",
      source="web",
      web_url=_web_url(3, "usenix.org/system/files/sec20-moghimi-tpm")),
    C("F3-019", 3, "Covert Channel — Storage vs Timing",
      "Storage: signal via shared resource state. Timing: signal via varying access timings. Both are unintentional disclosure paths.",
      source="web",
      web_url=_web_url(3, "examcollection.com/blog/cissp-exam-prep-deep-dive-into-covert-channel")),
    C("F3-020", 3, "Fire Classes",
      "A: ordinary combustibles (water). B: flammable liquids/gas. C: electrical (no water!). D: combustible metals. K: cooking oils.",
      source="guide", guide_pages=[920, 924]),
    C("F3-021", 3, "CPTED",
      "Crime Prevention Through Environmental Design: natural surveillance, natural access control, territorial reinforcement.",
      source="guide", guide_pages=[915, 920]),
    C("F3-022", 3, "Saltzer-Schroeder Principles (subset)",
      "Least privilege, fail-safe defaults, complete mediation, open design, separation of privilege, least common mechanism, psychological acceptability, economy of mechanism.",
      source="guide", guide_pages=[778, 783]),
    C("F3-023", 3, "ASLR + DEP",
      "ASLR = randomise memory layout; DEP/NX = mark data pages non-executable. Combined OS hardening against memory-corruption exploits.",
      source="canonical"),
    C("F3-024", 3, "Post-Quantum Crypto (NIST 2024)",
      "FIPS 203 ML-KEM (Kyber), 204 ML-DSA (Dilithium), 205 SLH-DSA (SPHINCS+) — first post-quantum standards.",
      source="canonical"),
    C("F3-025", 3, "PFS",
      "Perfect Forward Secrecy: compromise of long-term key cannot decrypt PAST sessions. Achieved via ephemeral key exchange (DHE/ECDHE).",
      source="canonical"),
]

# Domain 4
CARDS += [
    C("F4-001", 4, "OSI Model (Layers 1-7)",
      "Physical, Data Link, Network, Transport, Session, Presentation, Application. Mnemonic: 'Please Do Not Throw Sausage Pizza Away'.",
      source="guide", guide_pages=[1090, 1095]),
    C("F4-002", 4, "TCP/IP Model",
      "Link, Internet, Transport, Application — collapsed alternative to OSI used in practice.",
      source="canonical"),
    C("F4-003", 4, "TLS 1.3",
      "Mandates forward secrecy, removes RSA key transport, AEAD ciphers only, faster handshake (1-RTT, 0-RTT optional).",
      source="web",
      web_url=_web_url(4, "datatracker.ietf.org/doc/html/rfc8446")),
    C("F4-004", 4, "IPsec AH vs ESP",
      "AH: integrity over IP header + payload (no confidentiality, BREAKS through NAT). ESP: payload confidentiality + integrity (NAT-T uses UDP/4500).",
      source="web",
      web_url=_web_url(4, "datatracker.ietf.org/doc/html/rfc4301")),
    C("F4-005", 4, "IPsec Modes",
      "Transport: protect payload, original IP header visible (host-to-host). Tunnel: encapsulate full packet (gateway-to-gateway).",
      source="canonical"),
    C("F4-006", 4, "DNSSEC",
      "DNS Security Extensions — cryptographic origin authentication and integrity for DNS responses (NOT confidentiality).",
      source="canonical"),
    C("F4-007", 4, "DoH vs DoT",
      "DoH: DNS over HTTPS (port 443; blends with web traffic; harder for enterprise inspection). DoT: DNS over TLS (port 853; visible to enterprise).",
      source="canonical"),
    C("F4-008", 4, "WPA3-Personal vs WPA2-PSK",
      "WPA3 uses SAE (Dragonfly) handshake, defeating offline dictionary attacks against captured handshakes; provides forward secrecy per session.",
      source="web",
      web_url=_web_url(4, "ironwifi.com/blogs/best-eap-methods-wifi")),
    C("F4-009", 4, "EAP Methods",
      "EAP-TLS (mutual cert), PEAP (server cert + tunnel), EAP-TTLS (server cert + flexible inner), EAP-FAST (PAC). EAP-MD5 obsolete.",
      source="web",
      web_url=_web_url(4, "techtarget.com/searchnetworking/feature/Choosing-the-right-flavor")),
    C("F4-010", 4, "Stateful vs NGFW",
      "Stateful tracks connections. NGFW adds application identification, integrated IPS, threat intelligence.",
      source="canonical"),
    C("F4-011", 4, "WAF",
      "Web Application Firewall — L7-specific, rules for SQLi/XSS/etc; OWASP Core Rule Set is common.",
      source="canonical"),
    C("F4-012", 4, "Zero Trust",
      "Assume the network is hostile; verify identity, device posture, context per request; least-privilege access per resource (NIST SP 800-207).",
      source="web",
      web_url=_web_url(4, "csrc.nist.gov/pubs/sp/800/207")),
    C("F4-013", 4, "Microsegmentation",
      "Fine-grained workload-to-workload policy controls limiting east-west lateral movement after compromise.",
      source="canonical"),
    C("F4-014", 4, "SDN",
      "Software-Defined Networking — decouples control plane from data plane; centralised programmatic control; controller is a SPOF.",
      source="canonical"),
    C("F4-015", 4, "VXLAN",
      "Virtual Extensible LAN — extends L2 over L3 underlay using UDP encapsulation; does NOT provide encryption by default.",
      source="canonical"),
    C("F4-016", 4, "Common Network Attacks",
      "ARP spoofing (L2), DNS poisoning, MAC flooding, Smurf (ICMP amplification), Fraggle (UDP), Teardrop (overlapping fragments), Ping of Death.",
      source="canonical"),
    C("F4-017", 4, "DMZ / Screened Subnet",
      "Isolated network segment for internet-facing services, separated from internal network by firewall(s).",
      source="canonical"),
    C("F4-018", 4, "VPN Types",
      "Site-to-site (IPsec, gateway-to-gateway), Remote-access (IPsec or SSL/TLS clientless), modern: WireGuard.",
      source="canonical"),
    C("F4-019", 4, "Email Anti-Spoofing Trio",
      "SPF (authorised IPs), DKIM (signed headers), DMARC (alignment + policy + reporting). All three together.",
      source="canonical"),
    C("F4-020", 4, "S/MIME vs SPF/DKIM/DMARC",
      "S/MIME = end-to-end content encryption + signature. SPF/DKIM/DMARC = envelope-level anti-spoofing.",
      source="canonical"),
    C("F4-021", 4, "IDS vs IPS",
      "IDS: detect + alert (passive). IPS: detect + actively block (inline). Performance and false-positive risk are higher for IPS.",
      source="canonical"),
    C("F4-022", 4, "DDoS Categories",
      "Volumetric (saturate bandwidth), Protocol (SYN flood), Application-layer (Slowloris, HTTP flood), Reflective amplification (DNS/NTP/memcached).",
      source="canonical"),
    C("F4-023", 4, "ZTNA",
      "Zero Trust Network Access — broker per-application access by identity/context without exposing broad network ranges.",
      source="canonical"),
    C("F4-024", 4, "NTP Importance",
      "Time sync is critical for log correlation, Kerberos ticket validity, certificate validation, and forensic timelines.",
      source="canonical"),
]

# Domain 5
CARDS += [
    C("F5-001", 5, "IAAA",
      "Identification, Authentication, Authorisation, Accounting (auditing) — the four-step access control flow.",
      source="guide", guide_pages=[1685, 1690]),
    C("F5-002", 5, "MFA Factors",
      "Something you know (password), Something you have (token), Something you are (biometric), sometimes Somewhere you are (location).",
      source="canonical"),
    C("F5-003", 5, "DAC",
      "Discretionary Access Control — owner grants access at their discretion (file-system ACLs).",
      source="canonical"),
    C("F5-004", 5, "MAC",
      "Mandatory Access Control — system enforces clearance + label policy; appropriate for classified environments.",
      source="canonical"),
    C("F5-005", 5, "RBAC",
      "Role-Based Access Control — permissions tied to roles; users inherit permissions through role membership.",
      source="canonical"),
    C("F5-006", 5, "ABAC",
      "Attribute-Based Access Control — decisions based on user, resource, action, environment attributes (e.g., XACML, AWS IAM, Azure Conditional Access).",
      source="canonical"),
    C("F5-007", 5, "Rule-Based Access Control",
      "System-wide rules apply uniformly regardless of identity (e.g., firewall ACLs).",
      source="canonical"),
    C("F5-008", 5, "Kerberos Components",
      "AS (authentication server), TGS (ticket-granting server), KDC (encompassing AS+TGS), TGT, service ticket, principal.",
      source="guide", guide_pages=[1780, 1786]),
    C("F5-009", 5, "Kerberos Time Sync",
      "Tickets time-bound; clock skew tolerance ~5 minutes default. NTP is operationally critical.",
      source="canonical"),
    C("F5-010", 5, "Kerberos Attacks",
      "Kerberoasting (offline-crack service-ticket ciphertext), Pass-the-Hash (NTLM), Golden Ticket (forge TGTs from KRBTGT), Silver Ticket (forge service tickets).",
      source="canonical"),
    C("F5-011", 5, "SAML",
      "XML-based federation. IdP authenticates and issues an assertion (authentication, attribute, authorisation) to the SP.",
      source="canonical"),
    C("F5-012", 5, "OAuth 2.0",
      "Delegated AUTHORISATION framework — issues access tokens to third-party apps. NOT authentication on its own.",
      source="web",
      web_url=_web_url(5, "datatracker.ietf.org/doc/html/rfc6749")),
    C("F5-013", 5, "OpenID Connect (OIDC)",
      "Authentication layer on top of OAuth 2.0; ID token is a JWT carrying identity claims.",
      source="canonical"),
    C("F5-014", 5, "JWT",
      "JSON Web Token — compact, URL-safe, signed (JWS) and optionally encrypted (JWE) token format.",
      source="canonical"),
    C("F5-015", 5, "RADIUS vs TACACS+",
      "RADIUS: UDP, password-only encryption, AuthN+AuthZ combined. TACACS+: TCP, full payload encryption, separated AAA, supports per-command auth.",
      source="canonical"),
    C("F5-016", 5, "FIDO2 / WebAuthn",
      "Hardware-backed cryptographic authenticator providing AAL3 verifier-impersonation resistance per NIST 800-63B.",
      source="web",
      web_url=_web_url(5, "csrc.nist.gov/pubs/sp/800/63/3")),
    C("F5-017", 5, "NIST 800-63B Password Guidance",
      "No mandatory composition rules, no routine forced expiration, ≥8 chars, check against breached-password corpus, support up to 64 chars.",
      source="web",
      web_url=_web_url(5, "csrc.nist.gov/pubs/sp/800/63/3")),
    C("F5-018", 5, "JIT Access",
      "Just-In-Time access — grant privileges only when needed, time-limited; eliminates standing privilege.",
      source="web",
      web_url=_web_url(5, "thorteaches.com/glossary/just-in-time-jit-access")),
    C("F5-019", 5, "PAM",
      "Privileged Access Management — vault credentials, broker sessions with recording, MFA, automatic rotation.",
      source="canonical"),
    C("F5-020", 5, "Biometric Errors",
      "FAR (false acceptance — security failure), FRR (false rejection — usability failure). CER/EER = crossover where they meet (lower is better).",
      source="guide", guide_pages=[1700, 1706]),
    C("F5-021", 5, "SCIM",
      "System for Cross-domain Identity Management — standard for provisioning users between IdP and SaaS providers.",
      source="canonical"),
    C("F5-022", 5, "Privilege Creep",
      "Accumulating rights as roles change without removing old permissions; mitigated by access reviews and HR-driven deprovisioning.",
      source="canonical"),
    C("F5-023", 5, "TOTP / HOTP",
      "Time-based / HMAC-based OTP — RFC 6238 / RFC 4226. Authenticator app generates, verifier checks locally.",
      source="canonical"),
    C("F5-024", 5, "AAL Levels (NIST 800-63B)",
      "AAL1 (single-factor), AAL2 (two-factor with replay resistance), AAL3 (hardware crypto, verifier-impersonation resistant — FIDO2).",
      source="web",
      web_url=_web_url(5, "csrc.nist.gov/pubs/sp/800/63/3")),
]

# Domain 6
CARDS += [
    C("F6-001", 6, "SAST",
      "Static Application Security Testing — analyse source/bytecode without execution. White-box. Finds patterns like SQLi, hardcoded secrets.",
      source="canonical"),
    C("F6-002", 6, "DAST",
      "Dynamic Application Security Testing — exercise running app from outside. Black-box. Finds runtime-manifest issues.",
      source="canonical"),
    C("F6-003", 6, "IAST",
      "Interactive AST — agent inside running app combines source visibility with runtime context.",
      source="canonical"),
    C("F6-004", 6, "Fuzzing",
      "Send malformed/unexpected inputs to surface input-handling defects (crashes, memory errors, parser bugs).",
      source="canonical"),
    C("F6-005", 6, "NIST 800-115 Pen Test Phases",
      "Planning, Discovery, Attack, Reporting (4 phases). PTES defines 7.",
      source="web",
      web_url=_web_url(6, "csrc.nist.gov/pubs/sp/800/115")),
    C("F6-006", 6, "Pen Test Box Types",
      "Black (no info — external attacker), Gray (partial info — insider), White (full info — insider with everything).",
      source="canonical"),
    C("F6-007", 6, "SOC Reports",
      "SOC 1: financial-reporting controls (ISAE 3402 equivalent). SOC 2: Trust Services Criteria. SOC 3: SOC 2 public summary.",
      source="canonical"),
    C("F6-008", 6, "SOC 2 Type I vs Type II",
      "Type I: design at point-in-time. Type II: design + operating effectiveness over period (typically 6-12 months). Type II preferred by relying parties.",
      source="canonical"),
    C("F6-009", 6, "Vulnerability Scan vs Pen Test",
      "Scans identify potential weaknesses (breadth). Pen tests exploit them to demonstrate impact (depth).",
      source="canonical"),
    C("F6-010", 6, "Authenticated vs Unauthenticated Scan",
      "Authenticated logs in to reveal host-level patches/configs. Unauthenticated sees only externally exposed surfaces.",
      source="canonical"),
    C("F6-011", 6, "KPI vs KRI",
      "KPI: performance metric (mean time to patch). KRI: risk-exposure metric (count of overdue critical vulnerabilities).",
      source="canonical"),
    C("F6-012", 6, "SIEM",
      "Security Information and Event Management — correlate cross-source events to detect attacks; produces alerts.",
      source="canonical"),
    C("F6-013", 6, "SOAR",
      "Security Orchestration, Automation, Response — playbook automation across tools (containment, enrichment, ticketing).",
      source="canonical"),
    C("F6-014", 6, "Red / Blue / Purple Team",
      "Red: offensive. Blue: defensive. Purple: collaborative — share red techniques to improve blue detection/response.",
      source="canonical"),
    C("F6-015", 6, "CVSS",
      "Common Vulnerability Scoring System — 0-10 severity (Base, Temporal, Environmental). Current v4.0.",
      source="canonical"),
    C("F6-016", 6, "MITRE ATT&CK",
      "Knowledge base of adversary tactics (TA), techniques (T), and procedures used in real attacks; standard for detection engineering.",
      source="canonical"),
    C("F6-017", 6, "BAS",
      "Breach and Attack Simulation — automated execution of attacker techniques to validate detection/prevention controls continuously.",
      source="canonical"),
    C("F6-018", 6, "Synthetic Transaction",
      "Scripted requests simulating user actions to monitor availability and correctness.",
      source="canonical"),
    C("F6-019", 6, "Code Review",
      "Manual peer review excels at logic/business-rule defects automated SAST misses; combine both.",
      source="canonical"),
    C("F6-020", 6, "Pen Test Authorisation",
      "Signed authorisation letter + rules of engagement before starting — without it, the test is unauthorised intrusion.",
      source="canonical"),
]

# Domain 7
CARDS += [
    C("F7-001", 7, "NIST 800-61 IR Phases (Rev 2)",
      "Preparation → Detection & Analysis → Containment, Eradication & Recovery → Post-Incident Activity.",
      source="web",
      web_url=_web_url(7, "nvlpubs.nist.gov/nistpubs/specialpublications/nist.sp.800-61r2")),
    C("F7-002", 7, "Order of Volatility (RFC 3227)",
      "CPU registers/cache → System memory → Network state → Disk → Remote logs → Backup tapes (most → least volatile).",
      source="guide", guide_pages=[2210, 2215]),
    C("F7-003", 7, "Chain of Custody",
      "Documented record of evidence from collection through court — every transfer, location, access logged. Required for admissibility.",
      source="guide", guide_pages=[2215, 2220]),
    C("F7-004", 7, "Evidence Types",
      "Best (original/primary), Secondary (copies), Hearsay (out-of-court statement), Demonstrative (charts/models), Circumstantial.",
      source="canonical"),
    C("F7-005", 7, "RAID 0",
      "Stripe across drives — performance boost, NO redundancy.",
      source="canonical"),
    C("F7-006", 7, "RAID 1",
      "Mirror — identical copies on two drives, survives one failure, 50% storage efficiency.",
      source="canonical"),
    C("F7-007", 7, "RAID 5",
      "Stripe with distributed parity — survives one failure, write penalty.",
      source="canonical"),
    C("F7-008", 7, "RAID 6",
      "Stripe with dual parity — survives TWO simultaneous failures.",
      source="canonical"),
    C("F7-009", 7, "RAID 10 (1+0)",
      "Mirror then stripe — fast and resilient; survives multiple failures if not in same mirror pair.",
      source="canonical"),
    C("F7-010", 7, "Hot Site",
      "Fully equipped, near-real-time data, ready in minutes/hours; highest cost, lowest RTO.",
      source="canonical"),
    C("F7-011", 7, "Warm Site",
      "Hardware ready, stale data, ~12-hour activation. Mid cost / mid RTO.",
      source="canonical"),
    C("F7-012", 7, "Cold Site",
      "Space and utilities only; equipment + data must be brought in. Cheapest, longest RTO.",
      source="canonical"),
    C("F7-013", 7, "Mobile Site",
      "Trailer with equipment driven to needed location.",
      source="canonical"),
    C("F7-014", 7, "Reciprocal Agreement",
      "Mutual aid pact between organisations — cheap but problematic (capacity, regional disasters, confidentiality).",
      source="canonical"),
    C("F7-015", 7, "Backup Types",
      "Full (everything), Differential (since last full — slower backup, faster restore), Incremental (since last backup — faster backup, slower restore).",
      source="canonical"),
    C("F7-016", 7, "3-2-1 Backup Rule",
      "3 copies, on 2 different media types, with 1 offsite. Modern variants add immutability (3-2-1-1-0).",
      source="canonical"),
    C("F7-017", 7, "MTBF vs MTTR",
      "MTBF: Mean Time Between Failures — reliability. MTTR: Mean Time To Repair — recoverability. Lower MTTR is better.",
      source="canonical"),
    C("F7-018", 7, "Change Advisory Board (CAB)",
      "Body that authorises changes balancing risk, business impact, security. Emergency CAB (eCAB) handles urgent changes.",
      source="guide", guide_pages=[2270, 2275]),
    C("F7-019", 7, "EDR vs Antivirus",
      "EDR provides continuous endpoint telemetry, behavioural detection, response (isolate/kill/retrieve), and forensic data — beyond static AV.",
      source="canonical"),
    C("F7-020", 7, "UEBA",
      "User & Entity Behaviour Analytics — baselines normal behaviour, alerts on deviations (impossible travel, unusual data access).",
      source="canonical"),
    C("F7-021", 7, "Honeypot",
      "Decoy system to attract, detect, and study attackers. Honeynet = whole network of decoys.",
      source="canonical"),
    C("F7-022", 7, "Standards of Proof",
      "Civil: preponderance (>50%). Criminal: beyond reasonable doubt. Administrative: clear and convincing. Warrants: probable cause.",
      source="canonical"),
    C("F7-023", 7, "Need-to-Know",
      "Restrict access by job-justified need, even when general clearance/role allows broader access.",
      source="canonical"),
    C("F7-024", 7, "Clipping Level",
      "Threshold below which monitoring suppresses alerts to reduce noise (e.g., ignore <5 failed logins).",
      source="canonical"),
]

# Domain 8
CARDS += [
    C("F8-001", 8, "Waterfall",
      "Linear SDLC — requirements → design → implementation → testing → deployment. No phase backtracking.",
      source="canonical"),
    C("F8-002", 8, "Agile",
      "Iterative SDLC — short cycles, customer feedback, working software each iteration (Scrum, Kanban, XP).",
      source="canonical"),
    C("F8-003", 8, "Spiral",
      "Risk-driven iterative SDLC — each cycle includes risk assessment.",
      source="canonical"),
    C("F8-004", 8, "DevSecOps",
      "Security embedded continuously across CI/CD with automation (SAST, DAST, SCA, IaC scan, secrets detection).",
      source="canonical"),
    C("F8-005", 8, "CMMI",
      "Capability Maturity Model Integration — five process maturity levels: Initial → Managed → Defined → Quantitatively Managed → Optimising.",
      source="canonical"),
    C("F8-006", 8, "OWASP SAMM",
      "Prescriptive software-security maturity framework: Governance, Design, Implementation, Verification, Operations × four levels.",
      source="web",
      web_url=_web_url(8, "owasp.org/www-project-samm")),
    C("F8-007", 8, "BSIMM",
      "Descriptive maturity model based on observed activities at member organisations (not prescriptive).",
      source="canonical"),
    C("F8-008", 8, "OWASP Top 10:2021 (selected)",
      "A01 Broken Access Control, A02 Cryptographic Failures, A03 Injection, A04 Insecure Design, A06 Vulnerable Components, A10 SSRF.",
      source="web",
      web_url=_web_url(8, "owasp.org/www-project-top-ten")),
    C("F8-009", 8, "TOCTOU",
      "Time-of-Check to Time-of-Use race condition — state changes between authorisation check and use (CWE-367).",
      source="web",
      web_url=_web_url(8, "cqr.company/web-vulnerabilities/time-of-check-to-time-of-use")),
    C("F8-010", 8, "Buffer Overflow Defenses",
      "Memory-safe languages (Rust, Go); bounds checking; ASLR + DEP/NX; stack canaries; safer APIs (snprintf vs strcpy).",
      source="canonical"),
    C("F8-011", 8, "SQL Injection Defense",
      "Parameterised queries / prepared statements treat input as data, not code — structurally prevents injection.",
      source="canonical"),
    C("F8-012", 8, "XSS Defense",
      "Context-aware output encoding (HTML body vs attribute vs JS) plus a strict Content Security Policy.",
      source="canonical"),
    C("F8-013", 8, "CSRF Defense",
      "Anti-CSRF tokens (synchroniser pattern) + SameSite cookies (Lax/Strict).",
      source="canonical"),
    C("F8-014", 8, "SSRF Defense",
      "Allow-list destinations, block private/metadata endpoints (169.254.169.254), use a controlled egress proxy.",
      source="canonical"),
    C("F8-015", 8, "ACID",
      "Database transaction properties: Atomicity, Consistency, Isolation, Durability.",
      source="canonical"),
    C("F8-016", 8, "Inference Attack",
      "Combine individually authorised queries to deduce unauthorised information.",
      source="canonical"),
    C("F8-017", 8, "Aggregation",
      "Combining individually low-classification data into a higher-classification whole.",
      source="canonical"),
    C("F8-018", 8, "Polyinstantiation",
      "Multiple records with the same primary key at different security levels — defends against inference via existence.",
      source="canonical"),
    C("F8-019", 8, "SBOM",
      "Software Bill of Materials — structured component inventory (SPDX or CycloneDX). Required by US EO 14028.",
      source="canonical"),
    C("F8-020", 8, "SCA",
      "Software Composition Analysis — scan dependencies for known CVEs and licence issues.",
      source="canonical"),
    C("F8-021", 8, "NIST SSDF (SP 800-218)",
      "Secure Software Development Framework: Prepare the Org, Protect the Software, Produce Well-Secured Software, Respond to Vulnerabilities.",
      source="web",
      web_url=_web_url(8, "csrc.nist.gov/pubs/sp/800/218")),
    C("F8-022", 8, "OWASP ASVS",
      "Application Security Verification Standard — three verification levels (1-3) of security requirements.",
      source="web",
      web_url=_web_url(8, "owasp.org/www-project-application-security-verification-standard")),
    C("F8-023", 8, "Privacy by Design",
      "Embed privacy from inception — minimisation, purpose limitation, default-private, transparency. Codified in GDPR Article 25.",
      source="canonical"),
    C("F8-024", 8, "API Authentication",
      "Service-to-service: OAuth 2.0 client_credentials with short-lived tokens, or mTLS for workload identity.",
      source="canonical"),
]

# ===========================================================================
# 2026 ROUND-2 ADDITIONS — high-recall facts for the final week
# ===========================================================================

CARDS += [
    # Domain 1
    C("F1-031", 1, "ISC2 Code of Ethics — canon ordering",
      "(1) Protect society, the common good, the necessary public trust and confidence, and the infrastructure. (2) Act honourably, honestly, justly, responsibly, and legally. (3) Provide diligent and competent service to principals. (4) Advance and protect the profession. Higher-ordered canons take precedence when canons conflict.",
      source="canonical"),
    C("F1-032", 1, "Risk Treatment Verb List",
      "Mitigate (apply controls), Avoid (stop the activity), Transfer (insure / share), Accept (decision-maker signs off).",
      source="canonical"),
    C("F1-033", 1, "Mandatory Vacation",
      "Force absence so a substitute can detect ongoing fraud, embezzlement, or unsafe practices that depend on continuous control by one individual.",
      source="canonical"),
    C("F1-034", 1, "Job Rotation",
      "Cross-train staff (resilience) AND surface long-running fraud or shortcuts when a substitute takes the role. Complements separation of duties.",
      source="canonical"),
    C("F1-035", 1, "Annualised Loss Expectancy (ALE) shortcut",
      "ALE = SLE × ARO. SLE = AV × EF. So ALE = AV × EF × ARO. Quick check: dollars per year.",
      source="canonical"),
    C("F1-036", 1, "Risk Appetite vs Tolerance",
      "Appetite = the risk an organisation is willing to ACCEPT in pursuit of its objectives. Tolerance = the variance from appetite that's still acceptable. Appetite is strategic; tolerance is operational.",
      source="canonical"),
    C("F1-037", 1, "Three-Lines Model (IIA)",
      "1st line: operational management owns and manages risk. 2nd line: risk and compliance functions monitor and challenge. 3rd line: internal audit provides independent assurance to the governing body.",
      source="canonical"),
    C("F1-038", 1, "ISA vs MOU vs SLA vs BPA",
      "ISA = interconnection security agreement (technical). MOU = memorandum of understanding (intent, no penalties). SLA = service level agreement (metrics + penalties). BPA = business partnership agreement.",
      source="canonical"),
    C("F1-039", 1, "Mandatory vs Voluntary Standards",
      "Mandatory: PCI-DSS (contractual), HIPAA (regulatory), SOX (regulatory), GDPR (regulatory). Voluntary: ISO 27001, NIST CSF, COBIT, ITIL.",
      source="canonical"),
    C("F1-040", 1, "Personal Privacy Standards",
      "GDPR (EU/UK), CCPA/CPRA (California), HIPAA (US healthcare), GLBA (US financial), FERPA (US education), PIPEDA (Canada), LGPD (Brazil), POPIA (South Africa).",
      source="canonical"),

    # Domain 2
    C("F2-021", 2, "FIPS 199 categorisation",
      "Categorise each information type by impact (Low / Moderate / High) for each of Confidentiality, Integrity, Availability — independently. The system inherits the HIGH-WATER MARK across information types per dimension.",
      source="canonical"),
    C("F2-022", 2, "Data Lifecycle (CRUD-S)",
      "Create → Read → Use/Process → Share → Store → Archive → Destroy. Each phase has distinct controls (e.g., classification at Create, encryption at Store, sanitisation at Destroy).",
      source="canonical"),
    C("F2-023", 2, "DLP Discovery vs Inline",
      "Discovery DLP scans existing repositories for sensitive data at rest. Inline DLP intercepts data in motion (network, email, endpoint) — preventing exfiltration in real time.",
      source="canonical"),
    C("F2-024", 2, "Confidential Computing",
      "Protects data IN USE via hardware-backed enclaves (Intel SGX, AMD SEV, ARM TrustZone, AWS Nitro Enclaves). The historically weakest of the three data states.",
      source="canonical"),
    C("F2-025", 2, "GDPR Article 5 Principles",
      "Lawfulness/fairness/transparency, Purpose limitation, Data minimisation, Accuracy, Storage limitation, Integrity/confidentiality (security), Accountability.",
      source="canonical"),
    C("F2-026", 2, "Data Maskingrap vs Tokenisation vs Encryption",
      "Masking = irreversibly redact for non-prod use (analytics-friendly). Tokenisation = surrogate value, vault lookup to reverse. Encryption = mathematically reversible with the key.",
      source="canonical"),

    # Domain 3
    C("F3-026", 3, "Saltzer & Schroeder — eight design principles",
      "Economy of mechanism, Fail-safe defaults, Complete mediation, Open design, Separation of privilege, Least privilege, Least common mechanism, Psychological acceptability.",
      source="canonical"),
    C("F3-027", 3, "Common Criteria EALs",
      "EAL1 functionally tested → EAL2 structurally tested → EAL3 methodically tested → EAL4 designed/tested/reviewed (commercial sweet spot) → EAL5 semiformally designed → EAL6 semiformally verified → EAL7 formally verified.",
      source="canonical"),
    C("F3-028", 3, "Symmetric Key Sizes (Recommended)",
      "AES-128 = 128-bit security (acceptable). AES-256 = 256-bit (recommended for long-lived data; halved by Grover to 128-bit post-quantum). 3DES is deprecated. DES is broken (56-bit).",
      source="canonical"),
    C("F3-029", 3, "Asymmetric Key Sizes (Equivalent Strength)",
      "RSA-2048 ≈ ECC-224 ≈ AES-112 (~112-bit security). RSA-3072 ≈ ECC-256 ≈ AES-128. RSA-15360 ≈ ECC-512 ≈ AES-256. ECC achieves equivalent security with much smaller keys.",
      source="canonical"),
    C("F3-030", 3, "Post-Quantum Standards (FIPS 2024)",
      "FIPS 203 = ML-KEM (Kyber) — key encapsulation. FIPS 204 = ML-DSA (Dilithium) — digital signatures. FIPS 205 = SLH-DSA (SPHINCS+) — hash-based signatures, conservative backup.",
      source="canonical"),
    C("F3-031", 3, "Diffie-Hellman vs RSA Key Exchange",
      "DH/ECDH provides forward secrecy through ephemeral keys (PFS). RSA key transport does NOT provide PFS — long-term key compromise reveals all past sessions. TLS 1.3 removed RSA key transport for this reason.",
      source="canonical"),
    C("F3-032", 3, "TPM vs HSM vs Secure Enclave",
      "TPM: motherboard chip for platform integrity / sealed storage. HSM: standalone appliance for high-volume crypto + key management. Secure Enclave: CPU-integrated isolated memory (Apple SE, Intel SGX).",
      source="canonical"),
    C("F3-033", 3, "Datacenter Temperature/Humidity (ASHRAE)",
      "Recommended: 64-81°F (18-27°C), 40-60% RH. Excess humidity → corrosion. Low humidity → ESD damage.",
      source="canonical"),
    C("F3-034", 3, "Datacenter Tier Classifications (Uptime Institute)",
      "Tier I: 99.671% uptime (basic). Tier II: 99.741% (redundant capacity). Tier III: 99.982% (concurrently maintainable, N+1). Tier IV: 99.995% (fault-tolerant, 2N+1).",
      source="canonical"),

    # Domain 4
    C("F4-025", 4, "Common Port Numbers (high-yield)",
      "FTP 20/21, SSH 22, Telnet 23, SMTP 25, DNS 53, DHCP 67/68, HTTP 80, POP3 110, NTP 123, IMAP 143, HTTPS 443, SMB 445, RDP 3389, MySQL 3306, PostgreSQL 5432.",
      source="canonical"),
    C("F4-026", 4, "Wireless Protocol Generations",
      "WEP (broken). WPA (TKIP). WPA2 (CCMP/AES, but PSK 4-way handshake brute-forceable offline). WPA3 (SAE/Dragonfly handshake — defeats offline dictionary attacks; 192-bit option for enterprise).",
      source="canonical"),
    C("F4-027", 4, "VPN Protocols Ranked",
      "Modern: WireGuard (lean, fast, audited), IPsec/IKEv2 (mature, NAT-T capable). Legacy: OpenVPN (TLS-based), SSL/TLS VPN (browser). Avoid: PPTP (broken), L2TP without IPsec (no encryption).",
      source="canonical"),
    C("F4-028", 4, "Firewall Generations",
      "Gen 1: packet filter (stateless). Gen 2: stateful inspection. Gen 3: application proxy. Gen 4: NGFW (app-aware, integrated IPS, threat intel). Modern: cloud-native + WAF + API gateway.",
      source="canonical"),
    C("F4-029", 4, "Network Attack Quick Identification",
      "ARP spoofing (L2 mismap). DNS poisoning (corrupt resolution). MAC flood (CAM exhaustion). SYN flood (half-open exhaustion). Smurf (ICMP broadcast amplification). Fraggle (UDP amplification). Teardrop (overlapping fragments). MITM (intercept + alter).",
      source="canonical"),
    C("F4-030", 4, "Zero Trust Pillars (NIST 800-207)",
      "All resources are protected. Communication secured regardless of network. Per-session access. Dynamic policy from observable state. Continuous monitoring. Strict authentication for every access. (Pre-condition: verify everything, trust nothing.)",
      source="canonical"),

    # Domain 5
    C("F5-025", 5, "Federation Roles",
      "User → Identity Provider (IdP, holds identity) → assertion → Service Provider (SP / Relying Party, accepts assertion). User authenticates ONCE at the IdP for many SPs.",
      source="canonical"),
    C("F5-026", 5, "OAuth 2.0 Grant Types",
      "Authorization Code (web apps with backend), PKCE (public clients — SPAs, mobile), Client Credentials (service-to-service), Device Code (TVs, IoT). Avoid: Implicit (deprecated), Resource Owner Password Credentials (anti-pattern).",
      source="canonical"),
    C("F5-027", 5, "Kerberos Attack Quick-Reference",
      "Pass-the-Hash: NTLM hash replay. Pass-the-Ticket: Kerberos ticket replay. Kerberoasting: offline-crack service ticket ciphertext. AS-REP Roasting: target accounts without preauth. Golden Ticket: forge TGTs from KRBTGT hash. Silver Ticket: forge service tickets from service hash.",
      source="canonical"),
    C("F5-028", 5, "FIDO2 / WebAuthn / CTAP",
      "FIDO2 = umbrella (WebAuthn + CTAP). WebAuthn = browser API for relying parties. CTAP = client-to-authenticator protocol. Together: phishing-resistant, AAL3-eligible authentication.",
      source="canonical"),
    C("F5-029", 5, "RBAC vs ABAC vs ReBAC vs PBAC",
      "RBAC: roles. ABAC: attributes (user × resource × env). ReBAC: relationships (Google Zanzibar style). PBAC: policy-based (often XACML/OPA). Modern stacks layer RBAC + ABAC.",
      source="canonical"),
    C("F5-030", 5, "Account Lockout Recommendations (NIST 800-63B)",
      "Rate-limit failed attempts; do NOT use overly aggressive lockouts (DoS risk); pair with breached-password blocklist; allow user-initiated unlock with strong recovery; capture and alert on lockout patterns.",
      source="canonical"),
    C("F5-031", 5, "SSO Risk Concentration",
      "One credential = many systems. Mitigations: MFA always, conditional access, anomaly detection, short session lifetimes, step-up auth for sensitive actions, monitoring for unusual SSO sign-ins.",
      source="canonical"),

    # Domain 6
    C("F6-021", 6, "SAST vs DAST vs IAST vs SCA",
      "SAST: static source-code analysis. DAST: dynamic external runtime testing. IAST: instrumented runtime (combines source visibility + runtime data). SCA: scans dependencies for known CVEs and licence issues.",
      source="canonical"),
    C("F6-022", 6, "Pen Test Box Quick Map",
      "Black box: no info (external attacker). Gray box: partial info (insider, compromised user). White box: full info (everything available).",
      source="canonical"),
    C("F6-023", 6, "SOC Report Quick Map",
      "SOC 1: financial-reporting controls (audit trail). SOC 2: AICPA TSC (security required + availability/confidentiality/processing-integrity/privacy elective). SOC 3: SOC 2 public summary. ISAE 3402 ≈ SOC 1; ISAE 3000 ≈ SOC 2.",
      source="canonical"),
    C("F6-024", 6, "Audit Opinion Hierarchy",
      "Unqualified (clean) > Qualified (issues but mostly OK) > Adverse (controls did NOT operate effectively) > Disclaimer (auditor couldn't opine). Customers want unqualified.",
      source="canonical"),
    C("F6-025", 6, "MITRE ATT&CK Tactic Sequence",
      "Reconnaissance → Resource Development → Initial Access → Execution → Persistence → Privilege Escalation → Defense Evasion → Credential Access → Discovery → Lateral Movement → Collection → Command & Control → Exfiltration → Impact.",
      source="canonical"),
    C("F6-026", 6, "Vulnerability Mgmt Cycle",
      "Identify (scan, threat intel) → Prioritise (CVSS + KEV + exposure) → Remediate (patch, mitigate, accept) → Verify (re-scan) → Report. Continuous, not annual.",
      source="canonical"),

    # Domain 7
    C("F7-025", 7, "RAID Level Quick Map",
      "RAID 0: stripe (perf, no redundancy). RAID 1: mirror (50% efficient). RAID 5: stripe + parity, 1-drive tolerance. RAID 6: dual parity, 2-drive tolerance. RAID 10: mirror + stripe (databases).",
      source="canonical"),
    C("F7-026", 7, "Backup Window Math",
      "RPO = 4h ↔ replicate or snapshot every ≤4h. RPO = 15min ↔ continuous log shipping. RPO = 24h ↔ daily backup. RPO drives BACKUP FREQUENCY.",
      source="canonical"),
    C("F7-027", 7, "Eradication vs Recovery (NIST 800-61)",
      "Eradicate: remove the cause (malware, attacker access, vulnerable configurations). Recovery: restore systems and data, verify integrity, return to operations. Eradication BEFORE recovery — otherwise you restore the compromise.",
      source="canonical"),
    C("F7-028", 7, "Forensic Toolkit Triad",
      "FTK / EnCase / X-Ways for disk imaging and analysis. Volatility for memory analysis. Wireshark / NetworkMiner for network capture. Always work on a forensic IMAGE, never the original — and always hash both.",
      source="canonical"),
    C("F7-029", 7, "Incident Severity Classifications",
      "Low: minimal impact, single user. Medium: business impact, multiple users. High: significant impact, customer-facing. Critical: organisation-wide, public/regulator-facing. Severity drives escalation path and team mobilisation.",
      source="canonical"),
    C("F7-030", 7, "BCP Doc Family",
      "BCP (overarching). DRP (technology recovery — subset). BIA (drives RTO/RPO). COOP (federal continuity). Crisis Comms Plan (messaging). Occupant Emergency Plan (life safety in the building).",
      source="canonical"),
    C("F7-031", 7, "Standards of Proof (Civil → Criminal)",
      "Probable cause (warrants/arrests). Preponderance of evidence (>50% — civil). Clear and convincing (administrative, some civil). Beyond reasonable doubt (criminal).",
      source="canonical"),

    # Domain 8
    C("F8-025", 8, "OWASP Top 10:2021 Memorisation Aid",
      "A01 Broken Access Control. A02 Cryptographic Failures. A03 Injection. A04 Insecure Design. A05 Security Misconfiguration. A06 Vulnerable Components. A07 Auth Failures. A08 Software/Data Integrity Failures. A09 Logging/Monitoring Failures. A10 SSRF.",
      source="canonical"),
    C("F8-026", 8, "Database Security Threats Quick Map",
      "Inference: deduce unauthorised info from authorised queries. Aggregation: combine low-classification records into high-classification whole. Polyinstantiation: same key, different value per classification. Bypass attack: skip the application, hit the DB directly.",
      source="canonical"),
    C("F8-027", 8, "Secure SDLC Phases",
      "Requirements (security reqs, threat model). Design (DFDs with trust boundaries, STRIDE/PASTA). Implementation (secure coding, SAST). Testing (DAST, fuzz, pen test). Deployment (config hardening, gates). Operations (monitoring, IR, patch).",
      source="canonical"),
    C("F8-028", 8, "API Security Top Risks (OWASP API Top 10)",
      "Broken object-level auth (BOLA), Broken auth, Excessive data exposure, Lack of rate limiting, Broken function-level auth, Mass assignment, Misconfiguration, Injection, Improper assets management, Insufficient logging.",
      source="canonical"),
    C("F8-029", 8, "Code Repository Hygiene Checklist",
      "Branch protection on main. Required reviews + CODEOWNERS. Signed commits. Pre-commit + CI secret scanning. SCA on every PR. Pinned dependencies. SBOM generation. Cosign-signed artefacts.",
      source="canonical"),
    C("F8-030", 8, "Container Security Layers",
      "Image: scan + sign + minimal base + non-root. Registry: private + auth + integrity. Runtime: policy enforcement (OPA Gatekeeper, Kyverno), capability dropping, read-only FS, no-host-network. Cluster: RBAC, network policies, secrets via vault.",
      source="canonical"),
    C("F8-031", 8, "Modern Authn for Apps",
      "Passwords: NIST 800-63B (no rotation, breach check, ≥8 chars). MFA: TOTP / FIDO2 / passkeys (avoid SMS where possible). Federation: OIDC for new apps, SAML for enterprise. Session: short-lived JWT + refresh + revocation list.",
      source="canonical"),
    C("F8-032", 8, "DevSecOps Toolchain Sample",
      "SCM: GitHub/GitLab. CI: GitHub Actions/GitLab CI. SAST: Semgrep/SonarQube. SCA: Snyk/Dependabot/Trivy. Secret scan: Gitleaks/Trufflehog. IaC scan: Checkov/tfsec/KICS. Container: Trivy/Grype + Cosign sign. Runtime: Falco/Sysdig.",
      source="canonical"),
]



def main() -> None:
    OUT.write_text(json.dumps(CARDS, indent=2))
    print(f"[+] {len(CARDS)} flashcards written to {OUT} ({OUT.stat().st_size/1024:.1f} KiB)")
    by_d = {}
    by_src = {}
    for c in CARDS:
        by_d[c["domain"]] = by_d.get(c["domain"], 0) + 1
        by_src[c["source"]] = by_src.get(c["source"], 0) + 1
    print("By domain:", dict(sorted(by_d.items())))
    print("By source:", by_src)


if __name__ == "__main__":
    main()
